oliverklee/ext-oelib

CHANGELOG.md
composer.json

This will allow TravisCI to run the corresponding unit tests, too.

[TASK] Require-dev static_info_tables

---

CHANGELOG.md
ext_localconf.php

Use $GLOBALS['TYPO3_CONF_VARS'] instead of $TYPO3_CONF_VARS

Adapt TYPO3_CONF_VARS configuration

---

CHANGELOG.md
Classes/Geocoding/Google.php
Tests/Unit/Geocoding/GoogleTest.php

Also reduce the throttling time as Google has changed their limits.

[BUGFIX] Use multiple attempts for failed geocoding

---

TestExtensions/user_oelibtest/ext_emconf.php
TestExtensions/user_oelibtest2/ext_emconf.php
ext_emconf.php

[CLEANUP] Drop the comments from the ext_emconf.php

---

Configuration/php-cs-fixer.php

[BUGFIX] Fix path in the php-cs-fixer configuration documentation

---

CHANGELOG.md
Classes/Attachment.php
Classes/BackEndLoginManager.php
Classes/ConfigCheck.php
Classes/Configuration.php
Classes/ConfigurationProxy.php
Classes/ConfigurationRegistry.php
Classes/DataMapper.php
Classes/EmailCollector.php
Classes/FakeSession.php
Classes/FrontEndLoginManager.php
Classes/Geocoding/Dummy.php
Classes/HeaderProxyFactory.php
Classes/IdentityMap.php
Classes/List.php
Classes/MailerFactory.php
Classes/MapperRegistry.php
Classes/Model.php
Classes/PageFinder.php
Classes/SalutationSwitcher.php
Classes/TemplateHelper.php
Classes/TemplateRegistry.php
Classes/Translator.php
Classes/Visibility/Node.php
Classes/Visibility/Tree.php

With current PHP versions, the garbage collector does not need our
help anymore.

[TASK] Drop all destructors

---

CHANGELOG.md
composer.json

Also add roave/security-advisories as a dev dependency.
Fixes #88

[BUGFIX] Add required PHP extension to the composer.json

---

CHANGELOG.md
Classes/ViewHelpers/GoogleMapsViewHelper.php
Documentation/Configuration/Index.rst
Tests/Unit/ViewHelpers/GoogleMapsViewHelperTest.php

[FEATURE] Add a configuration for the Google Maps API key

---

Classes/TemplateHelper.php
Tests/Unit/DataMapperTest.php
ext_emconf.php

Also require PHP >= 5.4 in the ext_emconf.php.

[BUGFIX] Restore compatibility with PHP 5.4

---

CHANGELOG.md
Classes/DataMapper.php
Classes/MapperRegistry.php
Tests/LegacyFunctional/DataMapperTest.php
Tests/LegacyUnit/Fixtures/TestingModel.php
Tests/LegacyUnit/MapperRegistryTest.php
Tests/Unit/Mapper/Fixtures/TestingMapper.php
Tests/Unit/Model/Fixtures/TestingModel.php

This paves the way for namespaced data mapper classes.

[BUGFIX] Create testing data mappers without eval

---

CHANGELOG.md
Classes/Domain/Repository/Traits/StoragePageAgnosticTrait.php
Tests/Unit/Domain/Fixtures/EmptyModel.php
Tests/Unit/Domain/Repository/Fixtures/ReadOnlyRepository.php
Tests/Unit/Domain/Repository/Traits/ReadOnlyTest.php
composer.json
ext_emconf.php

Also streamline the existing test for the ReadOnlyRepository trait.

[FEATURE] Trait for storage-page-agnostic repositories

---

CHANGELOG.md
Classes/Domain/Repository/GermanZipCodeRepository.php
Tests/Functional/Domain/Repository/GermanZipCodeRepositoryTest.php

- directly return null for ZIP codes that don't have 5 digits
- cache the results

[TASK] Improve performance of the GermanZipCodeRepository

---

Tests/Functional/Configuration/PageFinderTest.php

[CLEANUP] Add missing null initializations to the page finder test

---

CHANGELOG.md
Classes/ConfigCheck.php

[BUGFIX] Fix a typo in a configuration check message

---

CHANGELOG.md
Classes/Domain/Repository/Interfaces/PersistAll.php
Classes/Domain/Repository/Traits/PersistAll.php
Tests/Unit/Domain/Repository/Fixtures/PersistAllRepository.php
Tests/Unit/Domain/Repository/Traits/PersistAllTest.php

Users of a repository should not need to be concerned with the
PersistenceManager.

[FEATURE] Trait and interface for Repository::persistAll

---

CHANGELOG.md
Tests/Functional/Mapper/AbstractDataMapperTest.php

- add `@doesNotPerformAssertions` to two tests
- add one missing comment
[ci skip]

[FOLLOWUP] Polish the tests

---

CHANGELOG.md
composer.json

[BUGFIX] Fix the casing of the vfsstream package

---

Tests/Unit/Model/FrontEndUserTest.php

[CLEANUP] Code autoformat

---

CHANGELOG.md
Classes/Model/FrontEndUser.php
Tests/Unit/Model/FrontEndUserTest.php

[BUGFIX] Remove dependency on specific extensions for the gender field

---

.travis.yml
CHANGELOG.md

Also properly quote the PHP version numbers as strings.

[BUGFIX] Explicitly require MySQL on Travis CI

---

CHANGELOG.md
Classes/ConfigCheck.php
Tests/Functional/Configuration/ConfigurationCheckTest.php

Also deprecated some configuration check methods.

[BUGFIX] Use the ConnectionPool for DB queries in ConfigCheck

---

CHANGELOG.md
Classes/DataMapper.php
Classes/Db.php
Tests/Functional/Mapper/AbstractDataMapperTest.php
Tests/Unit/Mapper/AbstractDataMapperTest.php
Tests/Unit/Mapper/Fixtures/TestingMapper.php

Also deprecate some methods in the DataMapper.

[TASK] Use the ConnectionPool in the DataMapper

---

CHANGELOG.md
Classes/TemplateHelper.php

This should improve performance and make real unit tests easier.

[TASK] Initialize the configuration in TemplateHelper lazily

---

Classes/SalutationSwitcher.php

[CLEANUP] Code cleanup in the salutation switcher

---

CHANGELOG.md
Classes/TemplateHelper.php

This should improve performance.

[TASK] Do not fetch the configuration without a page UID

---

.travis.yml
CHANGELOG.md

[TASK] Use PHP 7.2 for the release script

---

CHANGELOG.md
Classes/FrontEndLoginManager.php
Classes/TestingFramework.php
Tests/Functional/Testing/FrameworkTest.php

[BUGFIX] Use the context API in TYPO3 9.5 for the FE login

---

CHANGELOG.md
Configuration/TCA/Overrides/fe_users.php
Configuration/TCA/tx_oelib_domain_model_germanzipcode.php
Configuration/TCA/tx_oelib_test.php
Configuration/TCA/tx_oelib_testchild.php
Configuration/php-cs-fixer.php
TestExtensions/user_oelibtest/Configuration/TCA/user_oelibtest_test.php
TestExtensions/user_oelibtest2/Configuration/TCA/user_oelibtest2_test.php
composer.json

Now the `php:fix` Composer script runs `phpcbf` in addition to
`php-cs-fixer`.

[BUGFIX] Improve the code autoformatting

---

.travis.yml
CHANGELOG.md

This fixes a warning on Travis CI.

[BUGFIX] Add dist to the .travis.yml

---

CHANGELOG.md
Classes/Email/SystemEmailFromBuilder.php

[CLEANUP] Use MailUtility in SystemEmailFromBuilder

---

CHANGELOG.md
Classes/TemplateHelper.php
Tests/Unit/Templating/TemplateHelperTest.php

Fixes https://github.com/oliverklee/ext-seminars/issues/463

[BUGFIX] Fix crash if no HTML template path is provided

---

CHANGELOG.md
Classes/Template.php
Tests/Unit/Templating/TemplateTest.php

[BUGFIX] Allow non-string marker contents in templates

---

composer.json

[TASK] Update the dev dependencies

---

CHANGELOG.md
Classes/TestingFramework.php
Tests/Functional/Testing/FrameworkTest.php
Tests/Unit/Testing/FrameworkTest.php

[Task] Move the testing framework dummy files typo3 temp

---

Classes/FrontEnd/UserWithoutCookies.php
Classes/TestingFramework.php
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php

[TASK] Migrate UserWithoutCookies to proper namespace

---

Classes/Geocoding/DummyGeocodingLookup.php
Classes/Geocoding/GeoCalculcator.php
Classes/Geocoding/GoogleGeocoding.php
Classes/TestingFrameworkCleanup.php
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Unit/Geocoding/DummyGeocodingLookupTest.php
Tests/Unit/Geocoding/GeoCalculcatorTest.php
Tests/Unit/Geocoding/GoogleGeocodingTest.php

[TASK] Migrate Geocoding to proper namespaces

---

Classes/BackEndLoginManager.php
Classes/FrontEndLoginManager.php
Classes/Mapper/BackEndUserGroupMapper.php
Classes/Mapper/BackEndUserMapper.php
Classes/Mapper/CountryMapper.php
Classes/Mapper/CurrencyMapper.php
Classes/Mapper/FederalStateMapper.php
Classes/Mapper/FrontEndUserGroupMapper.php
Classes/Mapper/FrontEndUserMapper.php
Classes/Mapper/LanguageMapper.php
Classes/Model/FrontEndUser.php
Classes/TestingFramework.php
Classes/ViewHelper/Price.php
Documentation/Tutorial/UsingAndPersistingDomainModels/Index.rst
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Functional/Authentication/BackEndLoginManagerTest.php
Tests/Functional/Authentication/FrontEndLoginManagerTest.php
Tests/Functional/Mapper/BackEndUserGroupMapperTest.php
Tests/Functional/Mapper/BackEndUserMapperTest.php
Tests/Functional/Mapper/CountryMapperTest.php
Tests/Functional/Mapper/CurrencyMapperTest.php
Tests/Functional/Mapper/FederalStateMapperTest.php
Tests/Functional/Mapper/FrontEndUserGroupMapperTest.php
Tests/Functional/Mapper/FrontEndUserMapperTest.php
Tests/Functional/Mapper/LanguageMapperTest.php
Tests/Functional/Model/BackEndUserTest.php
Tests/Functional/Model/FrontEndUserTest.php
Tests/Unit/Mapper/Fixtures/TestingMapper.php
Tests/Unit/Model/FrontEndUserTest.php

[TASK] Migrate the mapper to proper namespace

---

Classes/ViewHelpers/GoogleMapsViewHelper.php
Classes/ViewHelpers/PriceViewhelper.php
Classes/ViewHelpers/UppercaseViewHelper.php
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Functional/ViewHelpers/PriceViewHelperTest.php
Tests/Unit/ViewHelpers/GoogleMapsViewHelperTest.php
Tests/Unit/ViewHelpers/PriceViewHelperTest.php
Tests/Unit/ViewHelpers/UppercaseViewHelperTest.php

[TASK] Migrate viewhelpers to proper namespace

---

Classes/Visibility/Node.php
Classes/Visibility/Tree.php
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Unit/Visibility/NodeTest.php
Tests/Unit/Visibility/TreeTest.php

[TASK] Migrate Visibilities to proper namespace

---

Classes/Mapper/AbstractDataMapper.php
Classes/Mapper/BackEndUserGroupMapper.php
Classes/Mapper/BackEndUserMapper.php
Classes/Mapper/CountryMapper.php
Classes/Mapper/CurrencyMapper.php
Classes/Mapper/FederalStateMapper.php
Classes/Mapper/FrontEndUserGroupMapper.php
Classes/Mapper/FrontEndUserMapper.php
Classes/Mapper/LanguageMapper.php
Classes/Mapper/MapperRegistry.php
Classes/Model.php
Documentation/Tutorial/UsingAndPersistingDomainModels/Index.rst
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Unit/Mapper/Fixtures/ColumnLessTestingMapper.php
Tests/Unit/Mapper/Fixtures/ModelLessTestingMapper.php
Tests/Unit/Mapper/Fixtures/TableLessTestingMapper.php
Tests/Unit/Mapper/Fixtures/TestingChildMapper.php
Tests/Unit/Mapper/Fixtures/TestingMapper.php

[CLEANUP] Migrate DataMapper and MapperRegistry to proper namespace

---

Classes/Geocoding/GeoCalculcator.php
Classes/IdentityMap.php
Classes/Interfaces/LoginManager.php
Classes/Mapper/AbstractDataMapper.php
Classes/Model/AbstractModel.php
Classes/Model/BackEndUser.php
Classes/Model/BackEndUserGroup.php
Classes/Model/Country.php
Classes/Model/Currency.php
Classes/Model/FederalState.php
Classes/Model/FrontEndUser.php
Classes/Model/FrontEndUserGroup.php
Classes/Model/Language.php
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Functional/Mapper/AbstractDataMapperTest.php
Tests/Functional/Model/AbstractModelTest.php
Tests/Unit/DataStructures/ListTest.php
Tests/Unit/Geocoding/Fixtures/TestingGeo.php
Tests/Unit/Mapper/AbstractDataMapperTest.php
Tests/Unit/Mapper/Fixtures/TestingMapper.php
Tests/Unit/Model/AbstractModelTest.php
Tests/Unit/Model/Fixtures/ReadOnlyModel.php
Tests/Unit/Model/Fixtures/TestingChildModel.php
Tests/Unit/Model/Fixtures/TestingModel.php

[CLEANUP] Migrate Tx_Oelib_Model to proper namespace

---

Classes/BackEndLoginManager.php
Classes/FrontEndLoginManager.php
Classes/Mapper/AbstractDataMapper.php
Classes/Mapper/MapperRegistry.php
Classes/Model/FrontEndUser.php
Classes/TestingFramework.php
Classes/TestingFrameworkCleanup.php
Classes/ViewHelpers/PriceViewhelper.php
Documentation/Tutorial/UsingAndPersistingDomainModels/Index.rst
Tests/Functional/Authentication/BackEndLoginManagerTest.php
Tests/Functional/Authentication/FrontEndLoginManagerTest.php
Tests/Functional/Mapper/AbstractDataMapperTest.php
Tests/Functional/Mapper/BackEndUserMapperTest.php
Tests/Functional/Mapper/FrontEndUserMapperTest.php
Tests/Functional/Model/AbstractModelTest.php
Tests/Functional/Model/BackEndUserTest.php
Tests/Functional/Model/FrontEndUserTest.php
Tests/Unit/Mapper/AbstractDataMapperTest.php
Tests/Unit/Mapper/MapperRegistryTest.php
Tests/Unit/Model/FrontEndUserTest.php

[CLEANUP] Migrate all occurences of Tx_Oelib_MapperRegistry to

---

Classes/List.php
Classes/Mapper/AbstractDataMapper.php
Documentation/Tutorial/UsingAndPersistingDomainModels/Index.rst

[CLEANUP][FOLLOWUP] Migrate left over Tx_Oelib_Model to namespaced class

---

Classes/Mapper/AbstractDataMapper.php
Classes/Mapper/IdentityMap.php
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Unit/Mapper/AbstractDataMapperTest.php
Tests/Unit/Mapper/Fixtures/TestingMapper.php
Tests/Unit/Mapper/IdentityMapTest.php

[CLEANUP] Migrate Tx_Oelib_IdentityMap to Mapper namespace

---

Classes/DataStructures/Collection.php
Classes/Interfaces/Time.php
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php

[CLEANUP] Migrate class Tx_Oelib_Time to Interface and namespace

---

Classes/Authentication/BackEndLoginManager.php
Classes/Authentication/FrontEndLoginManager.php
Classes/Mapper/BackEndUserMapper.php
Classes/TestingFramework.php
Classes/TestingFrameworkCleanup.php
Classes/TranslatorRegistry.php
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Functional/Authentication/BackEndLoginManagerTest.php
Tests/Functional/Authentication/FrontEndLoginManagerTest.php
Tests/Functional/Language/TranslatorRegistryTest.php
Tests/Functional/Testing/FrameworkTest.php
Tests/Unit/Authentication/BackEndLoginManagerTest.php
Tests/Unit/Authentication/FrontEndLoginManagerTest.php

[CLEANUP] Migrate the FE-/BELoginManager to proper namespace

---

Classes/Configuration/Configuration.php
Classes/Configuration/ConfigurationCheck.php
Classes/Configuration/ConfigurationProxy.php
Classes/Configuration/ConfigurationRegistry.php
Classes/Configuration/PageFinder.php
Classes/Geocoding/GoogleGeocoding.php
Classes/TemplateHelper.php
Classes/TestingFrameworkCleanup.php
Classes/TranslatorRegistry.php
Classes/ViewHelpers/GoogleMapsViewHelper.php
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Functional/Configuration/ConfigurationCheckTest.php
Tests/Functional/Configuration/ConfigurationRegistryTest.php
Tests/Functional/Configuration/PageFinderTest.php
Tests/Functional/Language/TranslatorRegistryTest.php
Tests/Functional/Templating/TemplateHelperTest.php
Tests/Unit/Configuration/ConfigurationCheckTest.php
Tests/Unit/Configuration/ConfigurationProxyTest.php
Tests/Unit/Configuration/ConfigurationRegistryTest.php
Tests/Unit/Configuration/ConfigurationTest.php
Tests/Unit/Configuration/PageFinderTest.php
Tests/Unit/Geocoding/GoogleGeocodingTest.php
Tests/Unit/Templating/Fixtures/TestingConfigurationCheck.php
Tests/Unit/Templating/TemplateHelperTest.php
Tests/Unit/ViewHelpers/GoogleMapsViewHelperTest.php

[CLEANUP] Migrate config related files to proper namespace

---

Classes/Http/HeaderCollector.php
Classes/Http/HeaderProxyFactory.php
Classes/Http/Interfaces/HeaderProxy.php
Classes/Http/RealHeaderProxy.php
Classes/TestingFrameworkCleanup.php
Documentation/Tutorial/StoreHttpHeadersForTestingThemInsteadOfSendingThem/Index.rst
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Unit/Http/HeaderProxyFactoryTest.php

[CLEANUP] Move Header classes to proper namespace

---

Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
composer.json

[TASK] Add Migrations/ to the PHP QualityTools

---

Classes/Database/DatabaseService.php
Classes/Mapper/AbstractDataMapper.php
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Functional/Database/DatabaseServiceTest.php

[CLEANUP] Rename Tx_Oelib_Db and migrate to proper namespace

---

Classes/Language/SalutationSwitcher.php
Classes/Language/Translator.php
Classes/Language/TranslatorRegistry.php
Classes/Template.php
Classes/TemplateHelper.php
Classes/TestingFrameworkCleanup.php
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Functional/Language/TranslatorRegistryTest.php
Tests/Unit/Language/Fixtures/TestingSalutationSwitcher.php
Tests/Unit/Language/TranslatorTest.php
Tests/Unit/Templating/TemplateTest.php

[CLEANUP] Move language related classes to proper namespace

---

Classes/Mail/AbstractMailer.php
Classes/Mail/Attachment.php
Classes/Mail/EmailCollector.php
Classes/Mail/Mail.php
Classes/Mail/MailerFactory.php
Classes/Mail/RealMailer.php
Classes/TestingFrameworkCleanup.php
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Functional/Email/AbstractMailerTest.php
Tests/Functional/Email/MailTest.php
Tests/Unit/Email/AbstractMailerTest.php
Tests/Unit/Email/AttachmentTest.php
Tests/Unit/Email/MailTest.php
Tests/Unit/Email/MailerFactoryTest.php
Tests/Unit/Email/RealMailerTest.php

[CLEANUP] Migrate mail related classes to proper namespace

---

Classes/Mail/Mail.php

[BUGFIX] Fix the path to the bundled autoload.php

---

Classes/Session/FakeSession.php
Classes/Session/Session.php
Classes/TestingFrameworkCleanup.php
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Unit/Session/FakeSessionTest.php
Tests/Unit/Session/SessionTest.php

[CLEANUP] Migrate session classes to proper namespace

---

Classes/Geocoding/GeoCalculator.php
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Unit/Geocoding/GeoCalculatorTest.php

[BUGFIX] Fix typo in class name "Calculcator"

---

Classes/Configuration/ConfigurationCheck.php
Classes/Templating/TemplateHelper.php
Classes/TestingFrameworkCleanup.php
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Unit/Configuration/Fixtures/DummyObjectToCheck.php
Tests/Unit/Templating/Fixtures/PluginWithCustomConfigurationCheck.php
Tests/Unit/Templating/Fixtures/TestingTemplateHelper.php
Tests/Unit/Templating/TemplateHelperTest.php

[CLEANUP] Move the TemplateHelper to namespaces

---

Classes/Templating/Template.php
Classes/Templating/TemplateHelper.php
Classes/Templating/TemplateRegistry.php
Classes/Visibility/Tree.php
Documentation/Tutorial/UsingTheTemplateHelperAndSalutationSwitching/Index.rst
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Unit/Templating/TemplateRegistryTest.php
Tests/Unit/Templating/TemplateTest.php

[CLEANUP] Migrate template related classes to proper namespace

---

Classes/Mapper/AbstractDataMapper.php
Classes/Mapper/MapperRegistry.php
Classes/Tests/TestingFramework.php
Classes/Tests/TestingFrameworkCleanup.php
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Functional/Authentication/FrontEndLoginManagerTest.php
Tests/Functional/Configuration/ConfigurationCheckTest.php
Tests/Functional/Configuration/ConfigurationRegistryTest.php
Tests/Functional/Configuration/PageFinderTest.php
Tests/Functional/Mapper/AbstractDataMapperTest.php
Tests/Functional/Mapper/BackEndUserMapperTest.php
Tests/Functional/Mapper/FrontEndUserGroupMapperTest.php
Tests/Functional/Testing/TestingFrameworkTest.php
Tests/Unit/Configuration/PageFinderTest.php
Tests/Unit/Testing/TestingFrameworkTest.php
ext_localconf.php

[CLEANUP] Move testing related classes to proper namespace

---

Documentation/Tutorial/UsingAndPersistingDomainModels/Index.rst
Documentation/Tutorial/UsingTheConfigurationProxy/Index.rst
Documentation/Tutorial/UsingThePriceViewHelper/Index.rst
Documentation/Tutorial/UsingTheVisibilityTreeForShowingAndHidingNestedSubparts/Index.rst
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Unit/Mapper/MapperRegistryTest.php

[CLEANUP] Sort the helper classes, update documentation and fix test

---

Classes/Mapper/AbstractDataMapper.php
Classes/Mapper/MapperRegistry.php
Classes/Testing/TestingFramework.php
Classes/Testing/TestingFrameworkCleanup.php
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Functional/Authentication/FrontEndLoginManagerTest.php
Tests/Functional/Configuration/ConfigurationCheckTest.php
Tests/Functional/Configuration/ConfigurationRegistryTest.php
Tests/Functional/Configuration/PageFinderTest.php
Tests/Functional/Mapper/AbstractDataMapperTest.php
Tests/Functional/Mapper/BackEndUserMapperTest.php
Tests/Functional/Mapper/FrontEndUserGroupMapperTest.php
Tests/Functional/Testing/TestingFrameworkTest.php
Tests/Unit/Testing/TestingFrameworkTest.php
ext_localconf.php

[CLEANUP] Rename the Tests namespace to Testing

---

Classes/Email/SystemEmailFromBuilder.php
Classes/Http/Interfaces/HeaderProxy.php

[TASK] Deprecate HeaderProxy and SystemEmailFromBuilder

---

Classes/Configuration/ConfigurationProxy.php
Classes/Configuration/ConfigurationRegistry.php
Classes/DataStructures/Collection.php
Classes/Database/DatabaseService.php
Classes/Domain/Model/GermanZipCode.php
Classes/Domain/Model/Traits/CachedAssociationCount.php
Classes/Domain/Repository/GermanZipCodeRepository.php
Classes/Email/EmailCollector.php
Classes/Email/Mail.php
Classes/Geocoding/DummyGeocodingLookup.php
Classes/Interfaces/Geo.php
Classes/Interfaces/MapPoint.php
Classes/Language/SalutationSwitcher.php
Classes/Language/Translator.php
Classes/Language/TranslatorRegistry.php
Classes/Mapper/AbstractDataMapper.php
Classes/Mapper/BackEndUserGroupMapper.php
Classes/Mapper/BackEndUserMapper.php
Classes/Mapper/CountryMapper.php
Classes/Mapper/FrontEndUserMapper.php
Classes/Mapper/IdentityMap.php
Classes/Mapper/MapperRegistry.php
Classes/Model/BackEndUser.php
Classes/Session/FakeSession.php
Classes/Session/Session.php
Classes/Templating/Template.php
Classes/Templating/TemplateHelper.php
Classes/Templating/TemplateRegistry.php
Classes/Testing/TestingFramework.php
Classes/Visibility/Node.php

This will help static code analysis.

[CLEANUP] Make the type annotations for arrays more specific

---

Tests/Unit/Domain/Fixtures/ParentModel.php

[TASK] Add the new @lazy annotation

---

Tests/Functional/Language/TranslatorRegistryTest.php

[TASK] Remove calls to initLLvars()

---

Classes/FrontEnd/UserWithoutCookies.php
Classes/Testing/TestingFramework.php

This removed a roadblock toward using PSR-4 autoloading.

[BUGFIX] Fix capitalization of namespaces

---

composer.json
ext_emconf.php
phpcs.xml.dist

[TASK] Remove namespace sniff exclusions and define PSR4

---

Classes/Authentication/FrontEndLoginManager.php
Classes/Database/DatabaseService.php
Classes/Email/SystemEmailFromBuilder.php
Classes/Mapper/AbstractDataMapper.php
Classes/Testing/TestingFramework.php

This helps static code analysis.

[CLEANUP] Add type annotations when using makeInstance

---

Classes/Testing/TestingFramework.php

[CLEANUP] Remove call to initTemplate()

---

Classes/Configuration/ConfigurationRegistry.php
Classes/Templating/TemplateHelper.php
Classes/Testing/TestingFramework.php

[CLEANUP] Stop calling $page->getRootLine in TYPO3 V9

---

CHANGELOG.md
Classes/Configuration/ConfigurationProxy.php

[CLEANUP] Update the configuration proxy to the new configuration format

---

Classes/Testing/TestingFramework.php

[CLEANUP] Stop accessing deprecated TypoScriptFrontendController properties

---

Classes/Configuration/ConfigurationRegistry.php
Classes/Templating/TemplateHelper.php

[CLEANUP] Stop calling $template->init in TYPO3 V9

---

Tests/Functional/Testing/TestingFrameworkTest.php

[CLEANUP] Use `Typo3Version::isNotHigherThan(8)` for version checking

---

Classes/Configuration/ConfigurationCheck.php
Classes/Templating/TemplateHelper.php

[CLEANUP] Stop using tmpl->getFileName

---

Classes/Configuration/ConfigurationCheck.php

[CLEANUP] Throw version-dependent deprecation warnings

---

Classes/Interfaces/Time.php

[BUGFIX] Fix the seconds per year constant

---

Tests/Unit/Interfaces/TimeTest.php

[TASK] Add test for the constants in Time interface

---

CHANGELOG.md
Classes/Database/DatabaseService.php
Classes/Domain/Repository/PageRepository.php
Tests/Functional/Domain/Repository/Fixtures/NestedPages.xml
Tests/Functional/Domain/Repository/PageRepositoryTest.php
Tests/Unit/Domain/Repository/PageRepositoryTest.php

This repository contains the replacement for
`DatabaseService::createRecursivePageList`.
Fixes #489

[FEATURE] Add a PageRepository

---

.github/workflows/ci.yml
.github/workflows/release.yml

This should speed up the CI workflow a bit.

[TASK] Disable Xdebug for GitHub actions

---

CHANGELOG.md
Classes/Geocoding/GeoCalculator.php
Tests/Unit/Geocoding/GeoCalculatorTest.php

[BUGFIX] Reduce the margin of GeoCalculator::moveByRandomDistance

---

Tests/Unit/ViewHelpers/PriceViewHelperTest.php

[CLEANUP] Use the AbstractViewHelperTest for VH tests

---

CHANGELOG.md
Configuration/TCA/Overrides/fe_users.php

[BUGFIX] Add a type in TCA for the FE users table dummy column

---

CHANGELOG.md
Classes/ViewHelpers/DynamicDateViewHelper.php
Tests/Unit/ViewHelpers/DynamicDateViewHelperTest.php

[FEATURE] Add a DynamicDateViewHelper

---

.editorconfig
CHANGELOG.md
Documentation/Settings.yml
README.md
Resources/Private/Language/de.locallang_db.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Language/locallang_db.xlf
Resources/Public/Icons/Extension.svg
Resources/Public/Icons/ZipCode.svg
composer.json

Also reformat the affected files.

[TASK] Adopt the .editorconfig settings from the TYPO3 Core

---

Tests/Unit/DataStructures/AbstractObjectWithPublicAccessorsTest.php
Tests/Unit/DataStructures/CollectionTest.php

Also fix some test name typos.

[CLEANUP] Drop some unnecessary test comment blocks

---

Tests/Unit/DataStructures/AbstractObjectWithPublicAccessorsTest.php

This helps the reader to see which data should be the same.

[CLEANUP] Use more variables in the tests

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php
Classes/Configuration/ConfigurationCheck.php
Classes/Templating/TemplateHelper.php
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Configuration/Fixtures/TestingConfigurationCheck.php

[FEATURE] Add a new basic configuration check

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php
Tests/Functional/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Configuration/Fixtures/TestingConfigurationCheck.php

[FEATURE] Add a configuration check for the template file

---

Classes/Configuration/AbstractConfigurationCheck.php
Classes/Configuration/ConfigurationCheck.php
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Configuration/Fixtures/TestingConfigurationCheck.php

Also drop tests for internal methods.
Part of #462

[FEATURE] Add set checks to the configuration check

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php
Classes/Configuration/ConfigurationCheck.php
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Configuration/Fixtures/TestingConfigurationCheck.php

[FEATURE] Add ConfigurationCheck::checkIfBoolean

---

Classes/Configuration/AbstractConfigurationCheck.php

These are hard to test, and we do not actually need them.
Part of #462

[TASK] Drop methods for value checks from ConfigurationCheck

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php
Classes/Configuration/ConfigurationCheck.php
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Configuration/Fixtures/TestingConfigurationCheck.php

[FEATURE] Add AbstractConfigurationCheck::checkIfIntegerInRange

---

Classes/Configuration/ConfigurationCheck.php
Classes/Configuration/ConfigurationRegistry.php
Classes/Templating/TemplateHelper.php
Tests/Functional/Templating/TemplateHelperTest.php
Tests/Unit/Language/Fixtures/TestingSalutationSwitcher.php
Tests/Unit/Templating/Fixtures/TestingTemplateHelper.php

This reduce the mental load when reading the code and the error messages
a bit.

[TASK] Stop abbreviating "TypoScript" as "TS"

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php
Classes/Configuration/ConfigurationCheck.php
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Configuration/Fixtures/TestingConfigurationCheck.php

[FEATURE] Add AbstractConfigurationCheck::checkIfPositiveInteger

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php

[CLEANUP] Reduce code duplication in AbstractConfigurationCheck

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php
Classes/Configuration/ConfigurationCheck.php
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Configuration/Fixtures/TestingConfigurationCheck.php

[FEATURE] Add multi-in-set checks to AbstractConfigurationCheck

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php
Classes/Configuration/ConfigurationCheck.php
Tests/Functional/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Configuration/Fixtures/TestingConfigurationCheck.php

[FEATURE] Add DB column configuration checks

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php
Classes/Configuration/ConfigurationCheck.php
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Configuration/Fixtures/TestingConfigurationCheck.php

[FEATURE] Add a salutation mode configuration check

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php
Classes/Configuration/ConfigurationCheck.php
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Configuration/Fixtures/TestingConfigurationCheck.php

[FEATURE] Add a regexp configuration check

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php
Classes/Configuration/ConfigurationCheck.php
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Configuration/Fixtures/TestingConfigurationCheck.php

[FEATURE] Add configuration check functions for integer lists

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php
Classes/Configuration/ConfigurationCheck.php

This will make moving from the old to the new configuration check
easier.
Part of #462.

[FEATURE] Add some deprecated methods to the new configuration check

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Configuration/Fixtures/TestingConfigurationCheck.php

[FEATURE] Add configuration check methods for email addresses

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php
Classes/Configuration/ConfigurationCheck.php
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Configuration/Fixtures/TestingConfigurationCheck.php

[FEATURE] Add a configuration check for the system email

---

CHANGELOG.md
phpstan-baseline.neon
phpstan.neon

[TASK] Raise PHPStan to level 1

---

CHANGELOG.md
Classes/Mapper/AbstractDataMapper.php
Classes/Mapper/BackEndUserGroupMapper.php
Classes/Mapper/BackEndUserMapper.php
Classes/Mapper/CountryMapper.php
Classes/Mapper/CurrencyMapper.php
Classes/Mapper/FederalStateMapper.php
Classes/Mapper/FrontEndUserGroupMapper.php
Classes/Mapper/FrontEndUserMapper.php
Classes/Mapper/LanguageMapper.php

[FEATURE] Use generics for the `DataMapper`

---

CHANGELOG.md
Classes/Configuration/FallbackConfiguration.php
Classes/DataStructures/AbstractObjectWithPublicAccessors.php
Classes/DataStructures/AbstractReadOnlyObjectWithAccessors.php
Classes/DataStructures/AbstractReadOnlyObjectWithPublicAccessors.php
Classes/Interfaces/Configuration.php
Tests/Unit/Configuration/FallbackConfigurationTest.php

[FEATURE] Add `ConfigurationInterface::getAsTrimmedArray`

---

CHANGELOG.md
Classes/Mapper/BackEndUserGroupMapper.php
Classes/Mapper/BackEndUserMapper.php
Classes/Mapper/FrontEndUserGroupMapper.php
Classes/Mapper/FrontEndUserMapper.php

[TASK] Make the user and group mappers as generic

---

CHANGELOG.md
Classes/Mapper/AbstractDataMapper.php
Classes/Mapper/MapperRegistry.php

[TASK] Annotate `MapperRegistry::get()` as a factory method

---

CHANGELOG.md
Classes/Http/HeaderProxyFactory.php
Tests/Unit/Http/HeaderProxyFactoryTest.php

[FEATURE] Add `HeaderProxyFactory::getHeaderCollector`

---

CHANGELOG.md
Classes/Mapper/BackEndUserMapper.php
Tests/Functional/Authentication/BackEndLoginManagerTest.php
Tests/Functional/Mapper/BackEndUserMapperTest.php
Tests/Functional/Mapper/Fixtures/BackEndUsers.xml
Tests/Unit/Mapper/BackEndUserMapperTest.php

Also clean up the tests for the class a bit.
Fixes #674

[BUGFIX] Stop relying on a BE user session in the `BackEndUserMapper`

---

CHANGELOG.md
Classes/Email/SystemEmailFromBuilder.php
Classes/Language/SalutationSwitcher.php
Classes/Templating/TemplateHelper.php
Classes/Testing/TestingFramework.php
Tests/Unit/Model/FrontEndUserTest.php
Tests/Unit/Templating/TemplateHelperTest.php

[BUGFIX] Fix issues with PHP 8.0

---

.github/workflows/ci.yml
CHANGELOG.md
composer.json
ext_emconf.php

[TASK] Drop support for PHP 7.0 and 7.1

---

.github/workflows/ci.yml
CHANGELOG.md
composer.json
ext_emconf.php

[TASK] Drop support for TYPO3 8LTS

---

.gitattributes
.github/workflows/ci.yml
.gitignore
.phive/phars.xml
CHANGELOG.md
composer.json
phpstan-baseline.neon

[TASK] Move PHPStan from PHIVE to Composer

---

CHANGELOG.md
Configuration/php-cs-fixer.php
Tests/Functional/Configuration/AbstractConfigurationCheckTest.php
Tests/Functional/Configuration/ConfigurationCheckTest.php
Tests/Functional/Email/MailTest.php
Tests/Functional/Mapper/AbstractDataMapperTest.php
Tests/Functional/Mapper/FrontEndUserMapperTest.php
Tests/Functional/Model/BackEndUserTest.php
Tests/Functional/Templating/TemplateHelperTest.php
Tests/Functional/Testing/TestingFrameworkTest.php
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Configuration/ConfigurationCheckTest.php
Tests/Unit/Configuration/DummyConfigurationTest.php
Tests/Unit/DataStructures/AbstractObjectWithPublicAccessorsTest.php
Tests/Unit/DataStructures/AbstractReadOnlyObjectWithAccessorsTest.php
Tests/Unit/DataStructures/CollectionTest.php
Tests/Unit/Email/AbstractMailerTest.php
Tests/Unit/Geocoding/GeoCalculatorTest.php
Tests/Unit/Geocoding/GoogleGeocodingTest.php
Tests/Unit/ViewHelpers/DynamicDateViewHelperTest.php
Tests/Unit/ViewHelpers/GoogleMapsViewHelperTest.php
composer.json
phpstan-baseline.neon

[TASK] Upgrade to PHPUnit 7

---

CHANGELOG.md
Classes/Authentication/FrontEndLoginManager.php
Classes/Configuration/ConfigurationCheck.php
Classes/Configuration/ConfigurationRegistry.php
Classes/Language/SalutationSwitcher.php
Classes/System/Typo3Version.php
Classes/Templating/TemplateHelper.php
Classes/Testing/TestingFramework.php
Tests/Functional/Configuration/ConfigurationRegistryTest.php
Tests/Functional/Testing/TestingFrameworkTest.php
Tests/Unit/System/Typo3VersionTest.php
Tests/Unit/Testing/TestingFrameworkTest.php

[TASK] Remove 8LTS-only code

---

CHANGELOG.md
Classes/Testing/TestingFramework.php

This communicates that this class is not intended to be mocked
or extended.
Fixes #495

[TASK] Make the testing framework class final

---

.gitignore
CHANGELOG.md
Tests/Unit/Mapper/Fixtures/TestingMapper.php
composer.json

[TASK] Upgrade to php-cs-fixer v3

---

.gitattributes
.github/workflows/ci.yml
.github/workflows/release.yml
CHANGELOG.md
composer.json
rector.php

[FEATURE] Add Rector to the CI toolchain

---

.github/workflows/ci.yml
CHANGELOG.md
composer.json

Rector produces too many false positives to always run it.

[TASK] Run Rector only on demand

---

CHANGELOG.md
Classes/Authentication/BackEndLoginManager.php
Classes/Authentication/FrontEndLoginManager.php
Classes/Configuration/ConfigurationCheck.php
Classes/Configuration/ConfigurationProxy.php
Classes/Configuration/ConfigurationRegistry.php
Classes/Configuration/TypoScriptConfiguration.php
Classes/DataStructures/Collection.php
Classes/Geocoding/GeoCalculator.php
Classes/Interfaces/Geo.php
Classes/Interfaces/LoginManager.php
Classes/Mapper/AbstractDataMapper.php
Classes/Mapper/CurrencyMapper.php
Classes/Mapper/FederalStateMapper.php
Classes/Templating/Template.php
Classes/Templating/TemplateHelper.php
Classes/Templating/TemplateRegistry.php
Classes/Testing/TestingFramework.php
rector.php

Also clean up the code annotations.

[BUGFIX] Disable Rector rulesets that break things

---

CHANGELOG.md
Classes/Domain/Repository/GermanZipCodeRepository.php
Classes/Domain/Repository/Traits/ReadOnlyRepository.php

[TASK] Deprecate the `ReadOnlyRepository` trait

---

CHANGELOG.md
Classes/Configuration/ConfigurationCheck.php
Classes/Domain/Model/GermanZipCode.php
Classes/Interfaces/Address.php
Classes/Interfaces/ConfigurationCheckable.php
Classes/Interfaces/MailRole.php
Classes/Language/SalutationSwitcher.php
Classes/Logging/Traits/LoggingAware.php
Classes/Model/AbstractModel.php
Classes/Session/Session.php
Tests/Unit/Model/Fixtures/TestingModel.php

[CLEANUP] Add more type declarations

---

CHANGELOG.md
Classes/Configuration/PageFinder.php
Classes/Geocoding/GeoCalculator.php
Classes/Geocoding/GoogleGeocoding.php
Classes/Interfaces/Time.php
Classes/Model/AbstractModel.php
Classes/Model/FrontEndUser.php
Classes/Session/Session.php
Classes/Templating/Template.php
Classes/Templating/TemplateHelper.php
Classes/Testing/TestingFramework.php
Classes/ViewHelpers/DynamicDateViewHelper.php
Classes/ViewHelpers/GoogleMapsViewHelper.php
Tests/Functional/Model/AbstractModelTest.php
Tests/Unit/Configuration/Fixtures/TestingConfigurationCheck.php
Tests/Unit/ViewHelpers/GoogleMapsViewHelperTest.php
phpcs.xml.dist

[CLEANUP] Add a visibility to all class constants

---

CHANGELOG.md
Classes/ViewHelpers/DynamicDateViewHelper.php
Classes/ViewHelpers/GoogleMapsViewHelper.php
Classes/ViewHelpers/PriceViewHelper.php
Tests/Unit/ViewHelpers/DynamicDateViewHelperTest.php
Tests/Unit/ViewHelpers/GoogleMapsViewHelperTest.php
Tests/Unit/ViewHelpers/PriceViewHelperTest.php
composer.json
phpstan.neon

[BUGFIX] Update the usage of the Fluid view helper classes

---

CHANGELOG.md
Classes/Domain/Model/Interfaces/ChangeDate.php
Classes/Domain/Model/Interfaces/CreationDate.php
Classes/Domain/Model/Traits/ChangeDate.php
Classes/Domain/Model/Traits/CreationDate.php
Tests/Unit/Domain/Model/Traits/ChangeDateTest.php
Tests/Unit/Domain/Model/Traits/CreationDateTest.php

[BUGFIX] Allow `DateTimeImmutable` as change and creation date

---

CHANGELOG.md
Classes/Templating/TemplateHelper.php
Classes/Testing/TestingFrameworkCleanup.php
Tests/Unit/Templating/TemplateHelperTest.php

[TASK] Drop `TemplateHelper::setCachedConfigurationValue()`

---

CHANGELOG.md
Classes/ViewHelpers/PriceViewHelper.php

[TASK] Deprecate the `PriceViewHelper`

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php

- add more top margin
- style it as a warning
Fixes #748
Fixes #746

[TASK] Improve the styling of the config check warnings

---

CHANGELOG.md
Classes/Configuration/FlexformsConfiguration.php
Tests/Unit/Configuration/FlexformsConfigurationTest.php

`AbstractPlugin` auto-converts the flexforms data from an array
to an array. We need to handle this.

[BUGFIX] Recognize flexforms data converted to an array

---

CHANGELOG.md
Tests/Functional/Testing/TestingFrameworkTest.php
Tests/Unit/DataStructures/CollectionTest.php
Tests/Unit/Testing/Fixtures/TestingCleanup.php
Tests/Unit/Testing/TestingFrameworkTest.php
phpstan-baseline.neon

[TASK] Fix all level 5 PHPStan warnings

---

CHANGELOG.md
phpstan-baseline.neon
phpstan.neon

[TASK] Raise PHPStan to level 6

---

CHANGELOG.md
Classes/Configuration/TypoScriptConfiguration.php
Tests/Functional/Configuration/ConfigurationRegistryTest.php
Tests/Unit/Configuration/ConfigurationRegistryTest.php
Tests/Unit/Configuration/TypoScriptConfigurationTest.php
Tests/Unit/Geocoding/GoogleGeocodingTest.php
Tests/Unit/ViewHelpers/GoogleMapsViewHelperTest.php

[TASK] Make the `TypoScriptConfiguration` immutable

---

CHANGELOG.md
Classes/Configuration/ConfigurationProxy.php
Tests/Functional/Templating/TemplateHelperTest.php
Tests/Unit/Configuration/ConfigurationProxyTest.php
phpstan-baseline.neon

[TASK] Make `ConfigurationProxy` immutable

---

.github/workflows/ci.yml
CHANGELOG.md
composer.json
ext_emconf.php

[FEATURE] Add support for TYPO3 10

---

CHANGELOG.md
composer.json

This improves compatibility with installations that use a higher
version.
Fixes #784

[TASK] Allow psr/log in versions 2 and 3 as well

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php
Classes/Configuration/ConfigurationCheck.php
Classes/DataStructures/AbstractReadOnlyObjectWithAccessors.php
Classes/Templating/Template.php
Classes/Testing/TestingFramework.php

[CLEANUP] Add some non-empty-string type annotations

---

CHANGELOG.md
Classes/DataStructures/Collection.php
Classes/Geocoding/GeoCalculator.php
Classes/Mapper/AbstractDataMapper.php
Classes/Model/AbstractModel.php
Classes/Model/FrontEndUser.php
Classes/Testing/TestingFramework.php
Tests/Functional/Mapper/AbstractDataMapperTest.php
Tests/Unit/DataStructures/CollectionTest.php
Tests/Unit/Geocoding/Fixtures/TestingGeo.php
Tests/Unit/Geocoding/GeoCalculatorTest.php
Tests/Unit/Model/BackEndUserGroupTest.php
Tests/Unit/Model/BackEndUserTest.php
Tests/Unit/Model/Fixtures/TestingModel.php
Tests/Unit/Model/FrontEndUserTest.php

[FEATURE] Add generics for the `Collection` class

---

CHANGELOG.md
phpstan-baseline.neon
phpstan.neon

[TASK] Raise PHPStan to level 7

---

CHANGELOG.md
Classes/Authentication/BackEndLoginManager.php
Classes/Authentication/FrontEndLoginManager.php
Classes/Interfaces/LoginManager.php
Tests/Unit/Authentication/BackEndLoginManagerTest.php
Tests/Unit/Authentication/FrontEndLoginManagerTest.php

Also allow all kinds of models as fake logged-in users.

[FEATURE] Add `LoginManager::getLoggedInUserUid()`

---

Classes/Configuration/AbstractConfigurationCheck.php

[TASK] Improve the documentation of `AbstractConfigurationCheck`

---

CHANGELOG.md
Classes/Testing/CacheNullifyer.php
Classes/Testing/TestingFramework.php
Tests/Functional/Testing/CacheNullifyerTest.php

[FEATURE] Add a `CacheNullifyer`

---

CHANGELOG.md
composer.json

[BUGFIX] Specify `app-dir` in the `composer.json`

---

CHANGELOG.md
Classes/Testing/TestingFramework.php

- provide the `cObj` with a `NullLogger`
- add `TYPO3_REQUEST_URL`

[BUGFIX] Add missing parts to the fake frontend

---

CHANGELOG.md
Classes/Testing/CacheNullifyer.php
Tests/Functional/Testing/CacheNullifyerTest.php

[BUGFIX] Fix the page cache identifyer for TYPO3 9LTS

---

CHANGELOG.md
Classes/Testing/CacheNullifyer.php

[BUGFIX] Also disable the core cache in TYPO3 9LTS

---

CHANGELOG.md
Tests/Unit/ViewHelpers/DynamicDateViewHelperTest.php
Tests/Unit/ViewHelpers/GoogleMapsViewHelperTest.php

[CLEANUP] Stop using deprecated PHPUnit functions

---

CHANGELOG.md
Classes/Configuration/ConfigurationCheck.php

[BUGFIX] Fix incorrect access to TSFE in the legacy config check

---

composer.json
phpstan-baseline.neon

Also regenerate the PHPStan baseline.
Also remove a leftover call from the `ci:static` Composer command.

[TASK] Update the development dependencies

---

.github/workflows/release.yml
CHANGELOG.md

[TASK] Switch the TER release to tailor

---

CHANGELOG.md
composer.json

[FEATURE] Remove dev-only files before releasing

---

Tests/Functional/Templating/TemplateHelperTest.php
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Domain/Repository/GermanZipCodeRepositoryTest.php
Tests/Unit/Domain/Repository/Traits/DirectPersistTest.php
Tests/Unit/Domain/Repository/Traits/ReadOnlyTest.php
Tests/Unit/Logging/Traits/LoggingAwareTest.php
Tests/Unit/Templating/TemplateHelperTest.php
composer.json

Also clean up the Prophecy usage a bit.

[TASK] Add the Prophecy PHPStan plugin

---

CHANGELOG.md
Classes/Domain/Model/Traits/CachedAssociationCount.php
Classes/Domain/Model/Traits/ChangeDate.php
Classes/Domain/Model/Traits/CreationDate.php
Classes/Domain/Model/Traits/LazyLoadingProperties.php
Classes/Domain/Repository/Traits/DirectPersist.php
Classes/Domain/Repository/Traits/StoragePageAgnostic.php
Classes/Logging/Traits/LoggingAware.php

This helps static code analysis.

[CLEANUP] Add `@mixin` annotations to traits

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php
Classes/Mapper/AbstractDataMapper.php
Classes/Mapper/BackEndUserGroupMapper.php
Classes/Mapper/BackEndUserMapper.php
Classes/Mapper/CountryMapper.php
Classes/Mapper/CurrencyMapper.php
Classes/Mapper/FederalStateMapper.php
Classes/Mapper/FrontEndUserGroupMapper.php
Classes/Mapper/FrontEndUserMapper.php
Classes/Mapper/LanguageMapper.php
Classes/Templating/Template.php
Classes/Templating/TemplateHelper.php
Classes/Testing/TestingFramework.php
Tests/Unit/Mapper/AbstractDataMapperTest.php
Tests/Unit/Mapper/Fixtures/ColumnLessTestingMapper.php
Tests/Unit/Mapper/Fixtures/ModelLessTestingMapper.php
Tests/Unit/Mapper/Fixtures/TestingChildMapper.php
Tests/Unit/Mapper/Fixtures/TestingMapper.php
Tests/Unit/Templating/TemplateHelperTest.php
phpstan-baseline.neon

[CLEANUP] Make some type annotations more specific

---

CHANGELOG.md
Classes/ViewHelpers/GoogleMapsViewHelper.php

[TASK] Deprecate `GoogleMapsViewHelper`

---

CHANGELOG.md
Classes/Domain/Repository/PageRepository.php
Tests/Functional/Domain/Repository/PageRepositoryTest.php

This fixes an SQL injection vulnerability.
Fixes #908

[SECURITY] Harden `PageRepository::findDirectSubpages`

---

CHANGELOG.md
Classes/Authentication/BackEndLoginManager.php
Classes/Authentication/FrontEndLoginManager.php
Classes/Configuration/AbstractConfigurationCheck.php
Classes/Configuration/ConfigurationRegistry.php
Classes/Configuration/PageFinder.php
Classes/Domain/Repository/GermanZipCodeRepository.php
Classes/Mapper/MapperRegistry.php
Classes/Templating/TemplateRegistry.php
Classes/Testing/TestingFramework.php
Classes/ViewHelpers/GoogleMapsViewHelper.php
phpstan-baseline.neon

[BUGFIX] Be more strict about booleans in conditions

---

Classes/Mapper/AbstractDataMapper.php
Tests/Unit/Mapper/Fixtures/TestingMapper.php
phpstan-baseline.neon

[CLEANUP] Add and use user-defined PHPStan types for DB results

---

CHANGELOG.md
Tests/Functional/Authentication/BackEndLoginManagerTest.php
Tests/Functional/Authentication/FrontEndLoginManagerTest.php
Tests/Functional/Configuration/AbstractConfigurationCheckTest.php
Tests/Functional/Configuration/ConfigurationRegistryTest.php
Tests/Functional/Configuration/PageFinderTest.php
Tests/Functional/Domain/Repository/GermanZipCodeRepositoryTest.php
Tests/Functional/Language/SalutationSwitcherTest.php
Tests/Functional/Mapper/AbstractDataMapperTest.php
Tests/Functional/Mapper/BackEndUserGroupMapperTest.php
Tests/Functional/Mapper/BackEndUserMapperTest.php
Tests/Functional/Mapper/CountryMapperTest.php
Tests/Functional/Mapper/CurrencyMapperTest.php
Tests/Functional/Mapper/FederalStateMapperTest.php
Tests/Functional/Mapper/FrontEndUserGroupMapperTest.php
Tests/Functional/Mapper/FrontEndUserMapperTest.php
Tests/Functional/Mapper/LanguageMapperTest.php
Tests/Functional/Model/AbstractModelTest.php
Tests/Functional/Model/BackEndUserTest.php
Tests/Functional/Model/FrontEndUserTest.php
Tests/Functional/Templating/TemplateHelperTest.php
Tests/Functional/Testing/CacheNullifyerTest.php
Tests/Functional/Testing/TestingFrameworkTest.php
Tests/Functional/Testing/WritableEnvironmentTest.php
Tests/Functional/ViewHelpers/PriceViewHelperTest.php
phpstan-baseline.neon

[CLEANUP] Relax some type annotations in the tests

---

CHANGELOG.md
Classes/ViewHelpers/DynamicDateViewHelper.php
Classes/ViewHelpers/GoogleMapsViewHelper.php
phpstan-baseline.neon

[BUGFIX] Avoid invalid array accesses in the view helpers

---

Classes/Mapper/AbstractDataMapper.php

[TASK] Avoid double-trimming a string

---

CHANGELOG.md
Classes/DataStructures/Collection.php
Tests/Unit/DataStructures/CollectionTest.php

[BUGFIX] Avoid crashes in `Collection` in PHP 8.1

---

CHANGELOG.md
Classes/FrontEnd/UserWithoutCookies.php
Classes/Testing/TestingFrameworkCleanup.php
Classes/Testing/WritableEnvironment.php

[TASK] Mark some internal classes as `@internal`

---

CHANGELOG.md
composer.json
ext_emconf.php

[TASK] Allow more versions of `static_info_tables`

---

CHANGELOG.md
Classes/Logging/Interfaces/LoggingAware.php
Classes/Logging/Traits/LoggingAware.php

[TASK] Deprecate the `LoggingAware` trait and interface

---

CHANGELOG.md
Classes/System/Typo3Version.php

[TASK] Deprecate `Typo3Version`

---

.github/workflows/ci.yml
.github/workflows/release.yml

[TASK] Upgrade the Ubuntu version for the GitHub CI runners

---

CHANGELOG.md
Classes/Mapper/AbstractDataMapper.php

[CLEANUP] Drop a redundant type annotation

---

CHANGELOG.md
Classes/Mapper/FrontEndUserMapper.php

[TASK] Deprecate `FrontEndUserMapper::getGroupMembers`

---

CHANGELOG.md
Tests/Unit/DataStructures/CollectionTest.php
Tests/Unit/Geocoding/DummyGeocodingLookupTest.php
Tests/Unit/Geocoding/GoogleGeocodingTest.php
Tests/Unit/ViewHelpers/DynamicDateViewHelperTest.php

[CLEANUP] Drop redundant type annotations for mocks

---

Classes/Domain/Model/Traits/CachedAssociationCount.php
Classes/Domain/Model/Traits/LazyLoadingProperties.php
Classes/Mapper/AbstractDataMapper.php
phpstan-baseline.neon

[CLEANUP] Annotate/fix intentional variable method/property accesses

---

CHANGELOG.md
Classes/Configuration/FlexformsConfiguration.php
Classes/Email/SystemEmailFromBuilder.php
Classes/Mapper/AbstractDataMapper.php
Classes/Model/AbstractModel.php
phpstan-baseline.neon

[CLEANUP] Drop redundant type casts

---

CHANGELOG.md
Classes/Configuration/FallbackConfiguration.php
Classes/Language/SalutationSwitcher.php
Classes/Mapper/AbstractDataMapper.php
Classes/Model/AbstractModel.php
Classes/Model/BackEndUser.php
Classes/Templating/Template.php
Classes/Templating/TemplateHelper.php
Classes/Testing/TestingFramework.php
Classes/ViewHelpers/GoogleMapsViewHelper.php
Tests/Unit/Geocoding/Fixtures/TestingGeo.php
phpstan-baseline.neon

[CLEANUP] Stop using the `empty()` construct

---

CHANGELOG.md
Tests/Functional/Mapper/BackEndUserGroupMapperTest.php
Tests/Functional/Mapper/CountryMapperTest.php
Tests/Functional/Mapper/CurrencyMapperTest.php
Tests/Functional/Mapper/FederalStateMapperTest.php
Tests/Functional/Mapper/FrontEndUserGroupMapperTest.php
Tests/Functional/Mapper/FrontEndUserMapperTest.php
Tests/Functional/Mapper/LanguageMapperTest.php
Tests/Unit/Mapper/BackEndUserGroupMapperTest.php
Tests/Unit/Mapper/CountryMapperTest.php
Tests/Unit/Mapper/CurrencyMapperTest.php
Tests/Unit/Mapper/FederalStateMapperTest.php
Tests/Unit/Mapper/FrontEndUserGroupMapperTest.php
Tests/Unit/Mapper/FrontEndUserMapperTest.php
Tests/Unit/Mapper/LanguageMapperTest.php
phpstan-baseline.neon

This improves test performance.
Fixes #673

[TASK] Convert some mapper tests to unit tests

---

CHANGELOG.md
Classes/Mapper/AbstractDataMapper.php
Classes/Mapper/MapperRegistry.php
Tests/Functional/Mapper/AbstractDataMapperTest.php
Tests/Unit/Mapper/Fixtures/ModelLessTestingMapper.php
Tests/Unit/Mapper/Fixtures/TestingMapper.php
Tests/Unit/Model/BackEndUserGroupTest.php
Tests/Unit/Model/BackEndUserTest.php
Tests/Unit/Model/Fixtures/TestingModel.php
Tests/Unit/Model/FrontEndUserTest.php
phpstan-baseline.neon
phpstan.neon

[CLEANUP] Use generics more loosely

---

CHANGELOG.md
Classes/Mapper/AbstractDataMapper.php

[TASK] Deprecate `AbstractDataMapper::countByPageUid`

---

CHANGELOG.md
Classes/DataStructures/Collection.php
Classes/Geocoding/GeoCalculator.php
Classes/Mapper/AbstractDataMapper.php
Classes/Model/AbstractModel.php
phpstan-baseline.neon

[BUGFIX] Improve the generics of `Collection`

---

CHANGELOG.md
phpstan-baseline.neon
phpstan.neon

[TASK] Raise PHPStan to level 9

---

CHANGELOG.md
Classes/Authentication/BackEndLoginManager.php
Classes/Authentication/FrontEndLoginManager.php
Classes/Configuration/AbstractConfigurationCheck.php
Classes/Configuration/ConfigurationRegistry.php
Classes/Configuration/FlexformsConfiguration.php
Classes/Configuration/PageFinder.php
Classes/DataStructures/Collection.php
Classes/Domain/Model/Traits/CachedAssociationCount.php
Classes/Domain/Repository/PageRepository.php
Classes/Http/HeaderCollector.php
Classes/Http/Interfaces/HeaderProxy.php
Classes/Language/SalutationSwitcher.php
Classes/Mapper/AbstractDataMapper.php
Classes/Mapper/BackEndUserMapper.php
Classes/Mapper/FrontEndUserMapper.php
Classes/Mapper/MapperRegistry.php
Classes/Model/AbstractModel.php
Classes/Model/BackEndUser.php
Classes/Model/FrontEndUser.php
Classes/Templating/Template.php
Classes/Templating/TemplateHelper.php
Classes/Templating/TemplateRegistry.php
Classes/Testing/TestingFramework.php
Classes/Visibility/Node.php
Tests/Functional/Mapper/FrontEndUserMapperTest.php
Tests/Unit/Model/BackEndUserTest.php
Tests/Unit/Model/FrontEndUserTest.php

[BUGFIX] Fix PhpStorm code inspection issues

---

CHANGELOG.md
Tests/Functional/Domain/Repository/GermanZipCodeRepositoryTest.php
Tests/Functional/Language/Fixtures/de.locallang.xlf
Tests/Functional/Language/Fixtures/fr.locallang.xlf
Tests/Functional/Language/Fixtures/locallang.xlf
Tests/Functional/Language/SalutationSwitcherTest.php
Tests/Functional/Model/AbstractModelTest.php
Tests/Functional/Templating/TemplateHelperTest.php
Tests/Functional/Testing/WritableEnvironmentTest.php
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Configuration/FallbackConfigurationTest.php
Tests/Unit/Configuration/Fixtures/TestingConfigurationCheck.php
Tests/Unit/DataStructures/AbstractObjectWithPublicAccessorsTest.php
Tests/Unit/DataStructures/AbstractReadOnlyObjectWithAccessorsTest.php
Tests/Unit/Geocoding/Fixtures/TestingGeo.php
Tests/Unit/Geocoding/GeoCalculatorTest.php
Tests/Unit/Model/AbstractModelTest.php
Tests/Unit/Model/Fixtures/TestingModel.php
Tests/Unit/Templating/TemplateHelperTest.php
Tests/Unit/Templating/TemplateTest.php

[CLEANUP] Fix PhpStorm code inspection issues in `Tests/`

---

Tests/Functional/Language/Fixtures/de.locallang.xlf
Tests/Functional/Language/Fixtures/fr.locallang.xlf
Tests/Functional/Language/Fixtures/locallang.xlf

This matches what the Core uses.

[CLEANUP] Switch the fixture XLIFF files indentation to tabs

---

Classes/ViewHelpers/GoogleMapsViewHelper.php
composer.json

Also drop redundant type casts that were only there on PHPStan's behest.

[TASK] Update to PHPStan 1.8.5

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php
Classes/Configuration/ConfigurationProxy.php
Classes/Configuration/DummyConfiguration.php
Classes/Configuration/FallbackConfiguration.php
Classes/Configuration/FlexformsConfiguration.php
Classes/Configuration/TypoScriptConfiguration.php
Classes/Interfaces/Configuration.php
Tests/Unit/Configuration/ConfigurationProxyTest.php
Tests/Unit/Configuration/DummyConfigurationTest.php
Tests/Unit/Configuration/FallbackConfigurationTest.php
Tests/Unit/Configuration/FlexformsConfigurationTest.php
Tests/Unit/Configuration/TypoScriptConfigurationTest.php

This allows the configuration check to be more specific on which
configuration to fix.

[FEATURE] Add a source name for the different configuration types

---

CHANGELOG.md
Classes/Language/SalutationSwitcher.php
Tests/Functional/Language/Fixtures/TestingSalutationSwitcher.php

[TASK] Deprecate the salutation-switching logic

---

CHANGELOG.md
Classes/Validation/AbstractConfigurationDependentValidator.php
Tests/Unit/Validation/AbstractConfigurationDependentValidatorTest.php
Tests/Unit/Validation/Fixtures/TestingConfigurationDependentValidator.php
Tests/Unit/Validation/Fixtures/TestingValidatableModel.php

[FEATURE] Add a configuration-dependent validator

---

CHANGELOG.md
Classes/Validation/AbstractConfigurationDependentValidator.php
Resources/Private/Language/de.locallang.xlf
Tests/Functional/Validation/AbstractConfigurationDependentValidatorTest.php

[TASK] Move localized validation messages from partial to validator

---

CHANGELOG.md
Classes/Validation/AbstractConfigurationDependentValidator.php
Tests/Functional/Validation/Fixtures/TestingConfigurationDependentValidator.php

This keeps devs from forgetting to set the class name.
Fixes #1079

[TASK] Make the validator more developer-friendly

---

CHANGELOG.md
Classes/Configuration/ExtbaseConfiguration.php
Classes/ViewHelpers/AbstractConfigurationCheckViewHelper.php
Tests/Unit/Configuration/ExtbaseConfigurationTest.php
Tests/Unit/ViewHelpers/AbstractConfigurationCheckViewHelperTest.php
Tests/Unit/ViewHelpers/Fixtures/TestingConfigurationCheck.php
Tests/Unit/ViewHelpers/Fixtures/TestingConfigurationCheckViewHelper.php
phpstan-baseline.neon

[FEATURE] Add an `AbstractConfigurationCheckViewHelper`

---

CHANGELOG.md
Classes/ViewHelpers/AbstractConfigurationCheckViewHelper.php

[TASK] Drop an unnecessary `render()` method from a view helper

---

CHANGELOG.md
Classes/Testing/TestingFramework.php
Tests/Functional/Testing/TestingFrameworkTest.php

[FEATURE] Allow data for `TestingFramework::createFrontEndPage()`

---

TestExtensions/user_oelibtest/composer.json
TestExtensions/user_oelibtest2/composer.json
composer.json

[CLEANUP] Normalize the `composer.json`

---

.github/workflows/ci.yml
composer.json

[FEATURE] Add composer normalize to the toolchain

---

CHANGELOG.md
Classes/Testing/CacheNullifyer.php
Classes/Testing/ExtendedGeneralUtility.php
Tests/Functional/Testing/CacheNullifyerTest.php
Tests/Unit/Testing/CacheNullifyerTest.php
Tests/Unit/Testing/ExtendedGeneralUtilityTest.php
Tests/Unit/Testing/Fixtures/TestingSubclass.php

[FEATURE] Add helper for clearing `GU::makeInstance()` class name cache

---

CHANGELOG.md
Classes/Domain/Model/GermanZipCode.php
Classes/Interfaces/Geo.php
Tests/Unit/Domain/Model/GermanZipCodeTest.php
Tests/Unit/Geocoding/Fixtures/TestingGeo.php

Also streamline the geocoding-related code a bit.
Fixes #893

[TASK] Make the geo coordinates nullable

---

CHANGELOG.md
Classes/Email/ConvertableToMimeAddressTrait.php
Classes/Email/GeneralEmailRole.php
Classes/Interfaces/ConvertableToMimeAddress.php
Classes/Model/BackEndUser.php
Classes/Model/FrontEndUser.php
Tests/Unit/Domain/Fixtures/ParentModel.php
Tests/Unit/Email/ConvertableToAddressTest.php
Tests/Unit/Email/GeneralEmailRoleTest.php
Tests/Unit/Email/TestingMimeConvertableMailRole.php
Tests/Unit/Model/BackEndUserTest.php
Tests/Unit/Model/FrontEndUserTest.php
composer.json

[FEATURE] Add a `ConvertableToMimeAddress` interface and trait

---

CHANGELOG.md
Classes/Model/AbstractModel.php
Tests/Unit/Model/AbstractModelTest.php

[TASK] Drop `AbstractModel::getAsList`

---

CHANGELOG.md
Classes/Mapper/AbstractDataMapper.php
phpstan-baseline.neon

[TASK] Drop `AbstractDataMapper::countByPageUid`

---

CHANGELOG.md
Classes/Testing/CacheNullifyer.php
Tests/Functional/Testing/CacheNullifyerTest.php

[TASK] Drop `CacheNullifyer::disableCoreCaches`

---

Tests/Unit/Email/ConvertableToAddressTest.php
Tests/Unit/Email/Fixtures/TestingMimeConvertableMailRole.php

[CLEANUP] Move `TestingMimeConvertableMailRole` to `Fixtures`

---

.github/workflows/ci.yml
CHANGELOG.md

[FEATURE] Run the tests on CI with TYPO3 11LTS as well

---

CHANGELOG.md
Classes/Testing/CacheNullifyer.php
Classes/Testing/TestingFramework.php
Tests/Functional/Testing/TestingFrameworkTest.php

[TASK] Drop `TestingFramework::disableCoreCaches`

---

CHANGELOG.md
Configuration/Services.yaml

[BUGFIX] Add a DI configuration

---

CHANGELOG.md
Configuration/TCA/tx_oelib_domain_model_germanzipcode.php
Configuration/TCA/tx_oelib_test.php
Configuration/TCA/tx_oelib_testchild.php

[BUGFIX] Drop `showRecordFieldList` from TCA in 11LTS

---

CHANGELOG.md
Tests/Unit/Authentication/FrontEndLoginManagerTest.php
Tests/Unit/Templating/TemplateHelperTest.php
Tests/Unit/Testing/TestingFrameworkTest.php

[BUGFIX] Properly purge the singleton instances in the tests

---

CHANGELOG.md
Configuration/Services.yaml

Followup to #1123
Part of #987

[BUGFIX] Fix the DI configuration

---

Tests/Unit/ViewHelpers/AbstractConfigurationCheckViewHelperTest.php
Tests/Unit/ViewHelpers/DynamicDateViewHelperTest.php
Tests/Unit/ViewHelpers/IsFieldEnabledViewHelperTest.php

Also improve the tests for the other view helpers a bit.

[TASK] Stop using the `ViewHelperBaseTestcase`

---

CHANGELOG.md
composer.json

[TASK] Add the TYPO3 testing framework to the toolchain

---

Tests/Functional/Mapper/AbstractDataMapperTest.php

[TASK] Replace COUNT queries in AbstractDataMapperTest

---

Tests/Functional/Mapper/AbstractDataMapperTest.php
Tests/Functional/Testing/TestingFrameworkTest.php

[TASK] Replace COUNT queries in `TestingFrameworkTest`

---

CHANGELOG.md
Classes/Testing/TestingFramework.php
Tests/Functional/Testing/TestingFrameworkTest.php

[TASK] Improve DB-related error message in the testing framework

---

CHANGELOG.md
Classes/Testing/TestingFramework.php

[TASK] Deprecate the testing framework auto increment functionality

---

Tests/Functional/Mapper/AbstractDataMapperTest.php
phpstan-baseline.neon

[TASK] Replace INSERT queries in `AbstractDataMapperTest`

---

Tests/Functional/Testing/TestingFrameworkTest.php
phpstan-baseline.neon

[TASK] Replace INSERT queries in `TestingFrameworkTest`

---

Tests/Functional/Testing/TestingFrameworkTest.php

[TASK] Replace DELETE queries in `TestingFrameworkTest`

---

CHANGELOG.md
README.md

[TASK] Add an 11LTS compatibility badge to the README

---

Tests/Functional/Mapper/AbstractDataMapperTest.php

[CLEANUP] Polish COUNT queries in `AbstractDataMapperTest`

---

Tests/Functional/Testing/TestingFrameworkTest.php
phpstan-baseline.neon

[TASK] Replace SELECT queries in `TestingFrameworkTest`

---

CHANGELOG.md
Classes/Testing/TestingFramework.php
Tests/Functional/Language/SalutationSwitcherTest.php
Tests/Functional/Testing/TestingFrameworkTest.php
Tests/Unit/Testing/TestingFrameworkTest.php

[TASK] Make the page UID for a fake frontend required

---

Tests/Functional/Model/BackEndUserTest.php
Tests/Functional/Templating/TemplateHelperTest.php
Tests/Functional/Testing/CacheNullifyerTest.php
Tests/Functional/Testing/WritableEnvironmentTest.php

This speeds up the tests a lot.
Fixes #1076

[TASK] Disable the DB in some functional tests

---

CHANGELOG.md
Classes/Visibility/Node.php
Classes/Visibility/Tree.php
Tests/Unit/Visibility/NodeTest.php
Tests/Unit/Visibility/TreeTest.php
phpstan-baseline.neon

This mostly reverts commit bd2bbb28ea88ab7406e69a45266b5220174de798.
Fixes #1191

[BUGFIX] Re-add and deprecate `Visibility\Tree` and `Visibility\Node`

---

CHANGELOG.md
Classes/Configuration/ConfigurationRegistry.php
phpstan-baseline.neon

[BUGFIX] Harden the `ConfigurationRegistry`

---

.github/workflows/ci.yml

[TASK] Switch code quality checks on CI to PHP 8.1

---

CHANGELOG.md
composer.json

[CLEANUP] Remove leftover TYPO3 9LTS dependencies

---

CHANGELOG.md
composer.json

[TASK] Raise the `symfony/mime` dependency

---

CHANGELOG.md
Tests/Unit/Domain/Model/Traits/CachedAssociationCountTest.php
Tests/Unit/Domain/Model/Traits/LazyLoadingPropertiesTest.php
Tests/Unit/Domain/Repository/GermanZipCodeRepositoryTest.php
Tests/Unit/Domain/Repository/Traits/DirectPersistTest.php

[TASK] Stop using Prophecy in the domain unit tests

---

CHANGELOG.md
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Logging/Traits/LoggingAwareTest.php
Tests/Unit/Session/SessionTest.php
Tests/Unit/Templating/TemplateHelperTest.php
Tests/Unit/ViewHelpers/AbstractConfigurationCheckViewHelperTest.php
Tests/Unit/ViewHelpers/DynamicDateViewHelperTest.php
Tests/Unit/ViewHelpers/IsFieldEnabledViewHelperTest.php

[TASK] Replace the remaining Prophecy usages in unit tests

---

CHANGELOG.md
Tests/Functional/Templating/TemplateHelperTest.php
Tests/Functional/Testing/TestingFrameworkTest.php

[TASK] Stop using Prophecy in the functional tests

---

.github/workflows/ci.yml
CHANGELOG.md
composer.json

[TASK] Drop the Prophecy dependency

---

Tests/Functional/Model/AbstractModelTest.php
Tests/Functional/Validation/AbstractConfigurationDependentValidatorTest.php
Tests/Unit/Geocoding/GeoCalculatorTest.php
Tests/Unit/Templating/TemplateTest.php
Tests/Unit/ViewHelpers/AbstractConfigurationCheckViewHelperTest.php
Tests/Unit/ViewHelpers/DynamicDateViewHelperTest.php
Tests/Unit/ViewHelpers/IsFieldEnabledViewHelperTest.php

[CLEANUP] Make properties in tests private where possible

---

CHANGELOG.md
Classes/Persistence/TestingQueryResult.php
Tests/Unit/Persistence/Fixtures/TestingModel.php
Tests/Unit/Persistence/TestingQueryResultTest.php

[FEATURE] Add a `TestingQueryResult` class

---

CHANGELOG.md
Classes/Model/FrontEndUser.php
Tests/Unit/Model/FrontEndUserTest.php

[FEATURE] Add a diverse gender option

---

CHANGELOG.md
Classes/Authentication/BackEndLoginManager.php
Classes/Authentication/FrontEndLoginManager.php
Classes/Domain/Model/Interfaces/ChangeDate.php
Classes/Domain/Model/Interfaces/CreationDate.php
Classes/Domain/Model/Traits/ChangeDate.php
Classes/Domain/Model/Traits/CreationDate.php
Classes/Exception/EmptyQueryResultException.php
Classes/Interfaces/LoginManager.php
Classes/Language/SalutationSwitcher.php
Classes/Mapper/BackEndUserGroupMapper.php
Classes/Mapper/BackEndUserMapper.php
Classes/Mapper/CountryMapper.php
Classes/Mapper/CurrencyMapper.php
Classes/Mapper/FederalStateMapper.php
Classes/Mapper/IdentityMap.php
Classes/Mapper/LanguageMapper.php
Classes/Model/BackEndUser.php
Classes/Model/BackEndUserGroup.php
Classes/Model/Country.php
Classes/Model/Currency.php
Classes/Model/FederalState.php
Classes/Model/FrontEndUser.php
Classes/Model/Language.php
Classes/Session/FakeSession.php
Classes/Session/Session.php
Classes/Templating/TemplateHelper.php

Also autoformat the affected classes.
Fixes #1110
Fixes #1122
Fixes #1160
Fixes #1161
Fixes #1238
Fixes #1244
Fixes #1251
Fixes #1264
Fixes #1268
Fixes #1270

[TASK] Deprecate some things

---

Documentation/Index.rst
Documentation/Settings.yml

[TASK] Change copyright year

---

.github/workflows/automerge.yml

[BUGFIX] Revert the GitHub action change

---

CHANGELOG.md
Classes/Testing/TestingFramework.php
Tests/Functional/Testing/TestingFrameworkTest.php

[CLEANUP] Improve the type annotations of the testing framework

---

CHANGELOG.md
Classes/Model/FrontEndUser.php

[TASK] Deprecate `FrontEndUser::getAge`

---

.gitattributes
CHANGELOG.md
composer.json

[FEATURE] Add the Crowdin configuration

---

CHANGELOG.md
Tests/Unit/Persistence/TestingQueryResultTest.php

This test relies on undefined behavior.

[BUGFIX] Drop a nonsensical test

---

CHANGELOG.md
Tests/Functional/Authentication/BackEndLoginManagerTest.php
Tests/Functional/Authentication/Fixtures/BackEndUser.csv

[BUGFIX] Avoid the deprecated `setUpBackendUserFromFixture`

---

CHANGELOG.md
Classes/Testing/CacheNullifyer.php
Tests/Functional/Testing/CacheNullifyerTest.php

[BUGFIX] Use a TYPO3-version-specific cache configuration again

---

CHANGELOG.md
Classes/Interfaces/Identity.php
Classes/Mapper/IdentityMap.php
Classes/Persistence/TestingQueryResult.php

[TASK] Mark some classes as `@internal`

---

CHANGELOG.md
Classes/Testing/DummyRequest.php
Tests/Unit/Testing/DummyRequestTest.php
composer.json

[FEATURE] Provide a `DummyRequest` for testing

---

CHANGELOG.md
Classes/Templating/TemplateHelper.php
Classes/Testing/TestingFramework.php

[BUGFIX] Stop accessing the `TYPO3_MODE` constant

---

CHANGELOG.md
Classes/Geocoding/DummyGeocodingLookup.php
Classes/Geocoding/GoogleGeocoding.php
Tests/Unit/Geocoding/DummyGeocodingLookupTest.php
Tests/Unit/Geocoding/GoogleGeocodingTest.php

[TASK] Deprecate the geocoding classes

---

CHANGELOG.md
Classes/Interfaces/Address.php
Classes/Model/FrontEndUser.php

[TASK] Deprecate some properties from `FrontEndUser`

---

CHANGELOG.md
Classes/DataStructures/Collection.php

[TASK] Mark `Collection::getUids()` as `@internal`

---

CHANGELOG.md
Classes/DataStructures/Collection.php

[TASK] Deprecate some `Collection` methods

---

CHANGELOG.md
Classes/ViewHelpers/DynamicDateViewHelper.php

[TASK] Deprecate the `DynamicDateViewHelper`

---

CHANGELOG.md
Classes/Http/HeaderCollector.php
Classes/Http/HeaderProxyFactory.php
Classes/Http/Interfaces/HeaderProxy.php
Classes/Http/RealHeaderProxy.php

[TASK] Deprecate the HTTP classes

---

CHANGELOG.md
Classes/Templating/TemplateHelper.php

Fixes #558
Fixes #559
Fixes #1448
Fixes #1449

[TASK] Deprecate `TemplateHelper`

---

CHANGELOG.md
Classes/Language/SalutationSwitcher.php

[TASK] Deprecate `SalutationSwitcher`

---

CHANGELOG.md
Classes/Domain/Model/Traits/CachedAssociationCount.php

[TASK] Deprecate `CachedAssociationCount`

---

CHANGELOG.md
Classes/DataStructures/Collection.php
Classes/Interfaces/Sortable.php

[TASK] Deprecate `Sortable`

---

CHANGELOG.md
Classes/Mapper/AbstractDataMapper.php

[TASK] Deprecate some methods from `AbstractDataMapper`

---

CHANGELOG.md
Classes/Mapper/BackEndUserMapper.php

[TASK] Deprecate `BackEndUserMapper::findByUserName`

---

CHANGELOG.md
Classes/Mapper/BackEndUserGroupMapper.php
Classes/Mapper/BackEndUserMapper.php
Classes/Model/BackEndUser.php
Classes/Model/BackEndUserGroup.php

[TASK] Deprecate `BackEndUser::getGroups` and `BackEndUserGroup`

---

CHANGELOG.md
Classes/Model/FrontEndUserGroup.php

[TASK] Deprecate `FrontEndUserGroup::title` and `::description`

---

CHANGELOG.md
Classes/Persistence/TestingQueryResult.php

[TASK] Deprecate `TestingQueryResult`

---

CHANGELOG.md
Classes/Testing/TestingFramework.php

[TASK] Deprecate the auto-increment handling in the testing framework

---

CHANGELOG.md
Classes/Testing/TestingFramework.php
Configuration/TCA/Overrides/fe_users.php
ext_tables.sql

[TASK] Deprecate the record change tracking in the testing framework

---

CHANGELOG.md
Classes/Testing/TestingFramework.php

[TASK] Deprecate the template parsing in the testing framework

---

CHANGELOG.md
Classes/Testing/TestingFramework.php

[TASK] Deprecate `TestingFramework::isLoggedIn()`

---

CHANGELOG.md
Classes/Testing/TestingFramework.php
ext_tables.sql

[TASK] Deprecate `TestingFramework::createBackEndUser()`

---

CHANGELOG.md
Classes/Mapper/CountryMapper.php
Classes/Mapper/LanguageMapper.php
Classes/Model/Country.php
Classes/Model/Language.php

[TASK] De-deprecate the `Country` and `Language` models and mappers

---

CHANGELOG.md
Classes/Testing/TestingFramework.php

Also de-deprecate it.
Fixes #1565

[TASK] Mark `TestingFramework::isLoggedIn()` as `@internal`

---

CHANGELOG.md
Classes/Mapper/AbstractDataMapper.php

[TASK] De-deprecate some things in `AbstractDataMapper` again

---

CHANGELOG.md
Classes/Testing/TestingFramework.php
Tests/Functional/Testing/TestingFrameworkTest.php

[TASK] Avoid additional query in `TestingFramework::changeRecord`

---

CHANGELOG.md
Classes/Mapper/AbstractDataMapper.php
Classes/Mapper/MapperRegistry.php

[TASK] Deprecate `MapperRegistry::denyDatabaseAccess`

---

CHANGELOG.md
composer.json

[TASK] Also drop TYPO3 10LTS from the `composer.json`

---

CHANGELOG.md
Classes/Model/FrontEndUser.php
Tests/Unit/Model/FrontEndUserTest.php

[TASK] Drop `FrontEndUser.wantsHtmlEmail()`

---

CHANGELOG.md
Classes/Mapper/BackEndUserMapper.php
Tests/Functional/Mapper/BackEndUserMapperTest.php
Tests/Functional/Mapper/Fixtures/BackEndUsers.xml
Tests/Unit/Mapper/BackEndUserMapperTest.php

[TASK] Drop `BackEndUserMapper::findByUserName`

---

Classes/Testing/TestingFramework.php
Tests/Functional/Configuration/ConfigurationRegistryTest.php
Tests/Functional/Testing/TestingFrameworkTest.php

[TASK] Drop the TypoScript template parsing from the testing framework

---

CHANGELOG.md
Classes/Testing/TestingFramework.php
Tests/Functional/Testing/TestingFrameworkTest.php
Tests/Unit/Testing/TestingFrameworkTest.php

[TASK] Make `TestingFramework::isLoggedIn()` private

---

CHANGELOG.md

[CLEANUP] Drop extraneous whitespace from the changelog

---

CHANGELOG.md
Classes/Mapper/AbstractDataMapper.php
Classes/Testing/TestingFramework.php
Configuration/TCA/Overrides/fe_users.php
Tests/Functional/Mapper/AbstractDataMapperTest.php
Tests/Functional/Testing/TestingFrameworkTest.php
Tests/Unit/Model/Fixtures/TestingChildModel.php
Tests/Unit/Model/Fixtures/TestingModel.php
ext_tables.sql
phpstan-baseline.neon

[TASK] Drop the tracking of changed records from the testing framework

---

CHANGELOG.md
Classes/Mapper/AbstractDataMapper.php
Classes/Mapper/MapperRegistry.php
Tests/Functional/Mapper/AbstractDataMapperTest.php
Tests/Unit/Mapper/AbstractDataMapperTest.php
Tests/Unit/Mapper/MapperRegistryTest.php

[TASK] Drop `MapperRegistry::denyDatabaseAccess`

---

Classes/Domain/Repository/GermanZipCodeRepository.php
Classes/Domain/Repository/PageRepository.php
Classes/Mapper/AbstractDataMapper.php
phpstan-baseline.neon

[TASK] Stop using the deprecated `$query->execute()`

---

CHANGELOG.md
composer.json
ext_emconf.php
phpstan-baseline.neon

[FEATURE] Allow installations with TYPO3 12LTS

---

.github/workflows/ci.yml
CHANGELOG.md

[FEATURE] Also run the CI pipelines with TYPO3 12LTS

---

.github/workflows/codecoverage.yml
CHANGELOG.md
README.md

[TASK] Switch the code coverage job to TYPO3 12LTS

---

Classes/Configuration/AbstractConfigurationCheck.php
phpstan-baseline.neon

[BUGFIX] Stop using more deprecated DBAL methods

---

CHANGELOG.md
Classes/Model/AbstractModel.php
Tests/Functional/Mapper/AbstractDataMapperTest.php
Tests/Unit/Model/AbstractModelTest.php
Tests/Unit/Model/FrontEndUserTest.php
phpstan-baseline.neon

[TASK] Use the `Context` for getting the current timestamp

---

CHANGELOG.md
Classes/Testing/TestingFramework.php
Tests/Functional/Testing/TestingFrameworkTest.php
phpstan-baseline.neon

[CLEANUP] Access the superglobals directly

---

CHANGELOG.md
Tests/Functional/Mapper/BackEndUserMapperTest.php
Tests/Functional/Mapper/Fixtures/BackEndUsers.csv
Tests/Functional/Mapper/Fixtures/BackEndUsers.xml

[TASK] Convert the BE user DB fixture from XML to CSV

---

CHANGELOG.md
Tests/Functional/Fixtures/Languages.csv
Tests/Functional/Mapper/LanguageMapperTest.php

[TASK] Convert the languages DB fixture from XML to CSV

---

CHANGELOG.md
Classes/Testing/TestingFramework.php
Tests/Functional/Testing/TestingFrameworkTest.php

It's now on Firefox 121.
Fixes #1698

[TASK] Update the faked user agent in the testing framework

---

.github/workflows/ci.yml

[FEATURE] Add Rector to CI

---

CHANGELOG.md
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/de.locallang_db.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Language/locallang_db.xlf

[BUGFIX] Add `resname` to all language labels

---

.github/dependabot.yml
composer.json

[TASK] Update composer-normalize

---

.github/workflows/automerge.yml
.github/workflows/ci.yml
.github/workflows/release.yml

[TASK] Switch the Ubuntu CI runners to 24.04

---

phpstan.neon

[TASK] Reduce redundancies in the PHPStan configuration

---

composer.json

[TASK] Drop `app-dir` from `composer.json`

---

rector.php

[TASK] Update the Rector configuration

---

CHANGELOG.md
Classes/Domain/Repository/Traits/DirectPersist.php
Classes/Domain/Repository/Traits/StoragePageAgnostic.php
phpstan-baseline.neon

[BUGFIX] Use proper annotations for traits with interfaces

---

CHANGELOG.md
Classes/DataStructures/Collection.php

[TASK] Drop unnecessary type checks

---

Tests/Functional/Configuration/AbstractConfigurationCheckTest.php
Tests/Functional/Configuration/ConfigurationRegistryTest.php
Tests/Functional/Configuration/PageFinderTest.php
Tests/Functional/Domain/Repository/GermanZipCodeRepositoryTest.php
Tests/Functional/Domain/Repository/PageRepositoryTest.php
Tests/Functional/Mapper/AbstractDataMapperTest.php
Tests/Functional/Mapper/BackEndUserMapperTest.php
Tests/Functional/Mapper/CountryMapperTest.php
Tests/Functional/Mapper/CurrencyMapperTest.php
Tests/Functional/Mapper/FrontEndUserMapperTest.php
Tests/Functional/Mapper/LanguageMapperTest.php
Tests/Functional/Model/AbstractModelTest.php
Tests/Functional/Templating/TemplateRegistryTest.php
Tests/Functional/Templating/TemplateTest.php
Tests/Functional/Testing/CacheNullifyerTest.php
Tests/Functional/Testing/TestingFrameworkTest.php
Tests/Functional/Testing/WritableEnvironmentTest.php
Tests/Functional/Validation/AbstractConfigurationDependentValidatorTest.php
Tests/Functional/ViewHelpers/PriceViewHelperTest.php

[TASK] Use the Composer keys for dependencies in functionals

---

CHANGELOG.md
Classes/Testing/CacheNullifyer.php

[BUGFIX] Use the correct cache frontend in the testing framework

---

.gitattributes
.github/dependabot.yml
.github/workflows/ci.yml
Build/bin/console
CHANGELOG.md
composer.json

[FEATURE] Add XLIFF linting to the CI workflow

---

.github/workflows/ci.yml
CHANGELOG.md
composer.json

[FEATURE] Add a Rector CI job

---

composer.json

[CLEANUP] Drop unnecessary `.Build/vendor/bin/` from Composer scripts

---

phpstan-baseline.neon
phpstan.neon

[TASK] Also check `ext_localconf.php` with PHPStan

---

.github/workflows/ci.yml

[FEATURE] Add a CI job for checking the docs rendering

---

CHANGELOG.md
composer.json

[TASK] Allow Fluid 4.0

---

CHANGELOG.md
Classes/Mapper/CurrencyMapper.php
Classes/Model/Currency.php

[TASK] Deprecate the `Currency` model and mapper

---

CHANGELOG.md
Classes/Mapper/AbstractDataMapper.php
Classes/Model/AbstractModel.php

[TASK] Deprecate `AbstractDataMapper::save()`

---

CHANGELOG.md
Classes/Mapper/BackEndUserMapper.php
Classes/Mapper/FrontEndUserGroupMapper.php
Classes/Mapper/FrontEndUserMapper.php
Classes/Model/BackEndUser.php
Classes/Model/FrontEndUser.php
Classes/Model/FrontEndUserGroup.php

[TASK] Deprecate `BackEndUser` and `FrontEndUserGroup`

---

CHANGELOG.md
Classes/Domain/Repository/Interfaces/DirectPersist.php
Classes/Domain/Repository/Traits/DirectPersist.php
Tests/Unit/Domain/Repository/Traits/Fixtures/DirectPersistRepository.php

[TASK] Deprecate the `DirectPersist` trait and interface

---

CHANGELOG.md
Classes/Domain/Repository/PageRepository.php

[TASK] Deprecate the `PageRepository`

---

CHANGELOG.md
Classes/Model/AbstractModel.php

[TASK] Deprecate the feature of readonly models

---

CHANGELOG.md
Classes/Domain/Repository/GermanZipCodeRepository.php
Classes/Domain/Repository/Traits/StoragePageAgnostic.php
Tests/Functional/Domain/Repository/GermanZipCodeRepositoryTest.php
phpstan-baseline.neon

[TASK] Deprecate the `StoragePageAgnostic` trait

---

CHANGELOG.md
Classes/Configuration/DummyConfiguration.php
Classes/Configuration/ExtbaseConfiguration.php
Classes/Configuration/FallbackConfiguration.php
Classes/Configuration/TypoScriptConfiguration.php
Classes/DataStructures/AbstractObjectWithAccessors.php
Classes/DataStructures/AbstractObjectWithPublicAccessors.php
Classes/DataStructures/AbstractReadOnlyObjectWithAccessors.php
Classes/DataStructures/AbstractReadOnlyObjectWithPublicAccessors.php
Classes/Interfaces/Configuration.php
Classes/Model/AbstractModel.php

[TASK] Improve some type annotations and PHPDoc comments

---

CHANGELOG.md
Classes/DataStructures/AbstractObjectWithPublicAccessors.php
Classes/DataStructures/AbstractReadOnlyObjectWithAccessors.php
Classes/DataStructures/AbstractReadOnlyObjectWithPublicAccessors.php
Classes/ViewHelpers/IsFieldEnabledViewHelper.php

[TASK] Fix some type annotations

---

Tests/Functional/Testing/TestingFrameworkTest.php
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/ViewHelpers/AbstractConfigurationCheckViewHelperTest.php
Tests/Unit/ViewHelpers/IsFieldEnabledViewHelperTest.php

This communicates the intent behind the code better.
Fixes #1476

[TASK] Use stubs instead of mocks where possible

---

Classes/Configuration/FallbackConfiguration.php
Tests/Unit/Configuration/FallbackConfigurationTest.php

[BUGFIX] Add `getAs*Integer` to `FallbackConfiguration`

---

CHANGELOG.md
Classes/Interfaces/Configuration.php

[BUGFIX] Add `getAs*Integer` to the `Configuration` interface

---

CHANGELOG.md
Classes/Model/AbstractModel.php
Classes/Model/Currency.php

[TASK] Simplify some range and type checks

---

phpstan-baseline.neon
phpstan.neon

This will help avoid it suggesting things that are only possile in later PHP versions.

[TASK] Configure the target PHP version for PHPStan

---

CHANGELOG.md
Classes/Configuration/ConfigurationProxy.php

[TASK] Deprecate the `ConfigurationProxy`

---

.github/workflows/ci.yml
.github/workflows/codecoverage.yml
.github/workflows/release.yml

In this case, we don't need to quote the strings.
https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml

[CLEANUP] Do not quote workflow/job names for GitHub actions
