oliverklee/ext-oelib

composer.json
ext_emconf.php

This is the earliest version available on Packagist.

[TASK] Recommende static_info_tables >= 6.3.7

---

CHANGELOG.md
Classes/SalutationSwitcher.php
Tests/Unit/SalutationSwitcherTest.php

This fixes a crash when mkforms tries to serialize the content object for
caching.

[BUGFIX] Make SalutationSwitcher/TemplateHelper serializable

---

CHANGELOG.md
composer.json

This fixes installation of this extension in TYPO3 6.2.

[BUGFIX] Drop the Composer dependency on emogrifier

---

Tests/Unit/AbstractMailerTest.php
Tests/Unit/MailerFactoryTest.php

In the unit tests, the deprecation log now does not need to be disabled
anymore.

[FOLLOWUP] Drop deprecated mailer functions

---

Classes/Geocoding/Google.php
Tests/Unit/Geocoding/GoogleTest.php
changelog.txt

The geocoding now starts with delay of 100ms and will stay under 120s
(the timeout for PHPUnit on Travis).
This is the 0.9.x backport part for #87.

[BUGFIX] Rework the geocoding throttling

---

CHANGELOG.md
Classes/Geocoding/Google.php
Tests/Unit/Geocoding/GoogleTest.php

Also update the domain in the API URL.

[BUGFIX] Remove the "sensor" parameter from the Google geocoding

---

Configuration/php-cs-fixer.php

This rule conflicts with the PhpStorm autoformatting.

[TASK] Drop the no_blank_lines_before_namespace php-cs-fixer rule

---

CHANGELOG.md

This dependency should only be in the project `composer.json`,
not in the dependency libraries.

[TASK] Drop roave/security-advisories from the dev dependencies

---

.travis.yml
CHANGELOG.md
Tests/Functional/HelloWorldTest.php
Tests/Unit/HelloWorldTest.php
composer.json

Also drop the 7.2 builds from Travis as the version of the testing framework
that still uses PHPUnit 5.x (which the PHPUnit extension currently provides)
does not work with PHP 7.2.

[FEATURE] Starter tests with nimut/testing-framework

---

Classes/MapperRegistry.php

Mapper class names now do not have any restrictions anymore.
[ci skip]

[TASK] Drop an obsolete comment

---

Tests/Unit/Domain/Fixtures/ChangedModel.php
Tests/Unit/Domain/Fixtures/CreatedModel.php
Tests/Unit/Domain/Model/Traits/ChangeDateTest.php
Tests/Unit/Domain/Model/Traits/CreationDateTest.php

The model fixtures are needed by both the model as well as the
repository tests.

[TASK] Move the model fixture one level higher

---

CHANGELOG.md
Classes/TestingFramework.php

This makes sure that during a deep cleanup, own tables without a dummy
column (e.g., new static tables) will not get cleaned up by the
testing framework.

[BUGFIX] Only clean up tables that have a dummy column

---

CHANGELOG.md
Classes/TemplateHelper.php

This works around inconsistencies between different autoloaders.

[BUGFIX] Allow mixed-case configuration check class names

---

CHANGELOG.md
Classes/DataMapper.php
Tests/LegacyFunctional/DataMapperTest.php

This is the 1.x backport of #194.

[BUGFIX] Ignore relations with a foreign UID of 0

---

changelog.txt
ext_tables.sql
ext_tables_static+adt.sql

The geo coordinates need to be saved as decimal, not as float.

[BUGFIX] Prevent rounding errors with the coordinates

---

CHANGELOG.md
Tests/LegacyUnit/BackEndLoginManagerTest.php

This fixes the tests with PHPUnit 5.7.

[BUGFIX] Always initialize a BE user in the BE user manager tests

---

CHANGELOG.md
composer.json

- drop an obsolete `replace` entry
- the the dependency on `roave/security-advisories` as this should
be in the distribution, not the individual extensions

[TASK] Streamline the composer.json dependencies

---

.travis.yml
CHANGELOG.md
composer.json

This should make version-dependent build failures less frequent.

[BUGFIX] Pin the dev dependency versions

---

CHANGELOG.md
Classes/Db.php
Classes/Domain/Repository/Traits/ReadOnlyTrait.php
Classes/Domain/Repository/Traits/StoragePageAgnosticTrait.php

On TYPO3 8.7, extensions might still call this method.

[TASK] Mark Db::getDatabaseConnection for removal in version 4.0, not 3.0

---

.travis.yml
CHANGELOG.md

This has been too much of a hassle due to breakage caused by old
dev dependencies.

[TASK] Stop building with the lowest Composer dependencies

---

.travis.yml
CHANGELOG.md
composer.json

Now that all tests are migrated to `nimut/testing-framework`, we
do not need the `oelib` extension for the tests anymore.

[TASK] Stop using the phpunit extension

---

.gitignore
CHANGELOG.md

This folder gets generated when running the tests in TYPO3 9LTS.

[BUGFIX] git-ignore the tests-generated var/log/ folder

---

CHANGELOG.md
Classes/Object.php

This avoids problems when persisting models with the ConnectionPool.

[BUGFIX] Internally store boolean properties as integers

---

CHANGELOG.md
Classes/Db.php

This avoids hazards when scripts run in parallel.

[BUGFIX] Always provide the table when getting the last insert ID

---

CHANGELOG.md

This messes up the dependencies too often. Caching the Composer cache
should be enough.

[BUGFIX] Do not cache vendor/ on Travis CI

---

.travis.yml
CHANGELOG.md

This combination currently does not work well yet.

[BUGFIX] Do not build with PHP 7.4 for TYPO3 8.7 on Travis CI

---

.travis.yml
CHANGELOG.md
composer.json

Now the CI build on Travis CI does not use the TYPO3 console anymore.

[TASK] Slim down the Travis setup

---

CHANGELOG.md
Classes/Db.php
Classes/FrontEndLoginManager.php
Classes/SalutationSwitcher.php
Classes/System/Typo3Version.php
Classes/TestingFramework.php
Tests/Unit/System/Typo3VersionTest.php

This allows version checks in TYPO3 8.7, 9.5 and 10.x.

[FEATURE] Add a TYPO3 version comparison class

---

CHANGELOG.md
composer.json

This avoids system-installed versions of the same tools
from getting called instead (which might be a different version and
also might not use our Composer autoloader).

[BUGFIX] Always use Composer-installed versions of the dev tools

---

CHANGELOG.md
Classes/TemplateHelper.php
Tests/Unit/Templating/TemplateHelperTest.php

This method was only used for testing itself, has no other use, and also
the tests using it did not make sense.

[TASK] Drop TemplateHelper::setCachedConfigurationValue

---

Classes/Testing/TestingFramework.php
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php

Also fix the used namespace in the migrations.
Also make the testing framework class non-final as long as we have
the legacy class for IDEs inhering from it.

[BUGFIX] More followup to namespacing all classes

---

CHANGELOG.md
Classes/Testing/TestingFramework.php

Cache keys in TYPO3 10LTS do not have the `cache_` prefix anymore.
Fixes #499

[BUGFIX] Use correct cache keys in TYPO3 10LTS

---

Classes/Testing/TestingFramework.php

[CLEANUP] Stop accessing deprecated TypoScriptFrontendController properties in TYPO3 9

---

CHANGELOG.md
Classes/Configuration/ConfigurationCheck.php
Classes/Configuration/ConfigurationRegistry.php
Classes/Configuration/PageFinder.php
Classes/Database/DatabaseService.php
Classes/Email/Mail.php
Classes/Email/MailerFactory.php
Classes/Geocoding/GoogleGeocoding.php
Classes/Mapper/AbstractDataMapper.php
Classes/Model/FrontEndUser.php
Classes/Session/Session.php
Classes/Templating/Template.php
Classes/Templating/TemplateHelper.php
Classes/ViewHelpers/PriceViewHelper.php

Whenever possible, use explicit `instanceof` calls instead.
This avoids false positives and helps static code analysis.

[CLEANUP] Harden null checks

---

CHANGELOG.md
Classes/Templating/TemplateHelper.php
Tests/Unit/Templating/TemplateHelperTest.php

This method is still used in the seminars tests.
This reverts commit da1d37035099b66aeda1a31afa9aa20dbe8a8c4e.
Fixes #526

[BUGFIX] Restore TemplateHelper::setCachedConfigurationValue

---

CHANGELOG.md
Classes/Configuration/Configuration.php
Classes/Configuration/ConfigurationProxy.php
Classes/DataStructures/AbstractObjectWithAccessors.php
Classes/Email/Mail.php
Classes/Model/AbstractModel.php
Classes/Session/FakeSession.php
Classes/Session/Session.php
Tests/Unit/DataStructures/Fixtures/TestingObject.php
Tests/Unit/Email/Fixtures/TestingMailRole.php

The `string` parameter type declaration in `AbstractObjectWithAccessors::set`
breaks the realty extension.
We'll add the type declaration for oelib 4.0.

[BUGFIX] Remove a breaking parameter type declaration

---

CHANGELOG.md
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php

It's `Tx_Oelib_Geocoding_Calculator`, not `Tx_Oelib_Geocoding_Calculcator`.

[BUGFIX] Fix a typo in a migration class alias

---

CHANGELOG.md
Classes/ViewHelpers/UppercaseViewHelper.php

There is a `format.case` view helper in Fluid, and we should not duplicate
that functionality.

[TASK] Deprecate the UppercaseViewHelper

---

.github/workflows/ci.yml

This allows us to see which PHP or TYPO3 versions we have broken with
a change.
Fixes #543

[TASK] Always build all CI matrix branches

---

CHANGELOG.md
Classes/Email/GeneralEmailRole.php
Classes/Email/SystemEmailFromBuilder.php
Classes/Interfaces/MailRole.php

These classes and the interface might still be useful, and they are not
affected by the coming switch from SwiftMailer to Symfony Mailer.
Fixes #542

[TASK] Don't deprecate EmailRole, GeneralEmailRole, SystemEmailFromBuilder

---

CHANGELOG.md
Classes/Model/AbstractModel.php
Tests/Unit/Model/AbstractModelTest.php

Also deprecate `::getAsList`.
Fixes #533

[FEATURE] Add AbstractModel::getAsCollection() as alias for ::getAsList

---

CHANGELOG.md
Classes/Configuration/ConfigurationRegistry.php
Classes/Configuration/TypoScriptConfiguration.php
Classes/Language/TranslatorRegistry.php
Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
Tests/Functional/Configuration/ConfigurationRegistryTest.php
Tests/Functional/Language/TranslatorRegistryTest.php
Tests/Unit/Configuration/ConfigurationRegistryTest.php
Tests/Unit/Configuration/TypoScriptConfigurationTest.php
Tests/Unit/Geocoding/GoogleGeocodingTest.php
Tests/Unit/ViewHelpers/GoogleMapsViewHelperTest.php

This make the difference to other configuration types more clear.
Fixes #556.

[TASK] Rename the Configuration class to TypoScriptConfiguration

---

CHANGELOG.md
Classes/Configuration/ConfigurationProxy.php
Classes/Configuration/ConfigurationRegistry.php
Tests/Unit/Configuration/ConfigurationProxyTest.php
Tests/Unit/Configuration/ConfigurationRegistryTest.php

This allows using the `DummyConfiguration` for tests with
TypoScript and extension configuration.
Fixes #566

[TASK] Use the interface in the configuration registry and proxy

---

CHANGELOG.md
Classes/Configuration/FlexformsConfiguration.php
Tests/Unit/Configuration/FlexformsConfigurationTest.php

There is no need to modify an existing Flexforms configuration
at runtime.
Fixes #563

[TASK] Make the FlexformsConfiguration read-only

---

Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Configuration/Fixtures/TestingConfigurationCheck.php

This should allow us to find errors in the test for the
configuration check faster.

[TASK] Throw an exception for an invalid check method in the tests

---

Classes/Configuration/ConfigurationCheck.php

The new alias methods `addWarningAndRequestCorrection` and
`addWarning` will make copy'n'paste when to the new
configuration check less of a pain.

[TASK] Add alias functions to ConfigurationCheck

---

Classes/Configuration/AbstractConfigurationCheck.php
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Configuration/Fixtures/TestingConfigurationCheck.php

`checkIfNonNegativeIntegerOrEmpty` more precisely describes what the
function does.
Part of #462.

[TASK] Rename ConfigurationCheck::checkIfInteger

---

CHANGELOG.md
Classes/Http/HeaderCollector.php
Classes/Http/HeaderProxyFactory.php
Classes/Http/Interfaces/HeaderProxy.php
Classes/Http/RealHeaderProxy.php

We cannot easily replace the calls to these classes in our code yet
as the `HttpUtility` methods are static, and we cannot easily switch
the `AbstractPlugin`-based classes to the new HTTP middleware.
Fixes #615

[TASK] De-deprecate the HTTP-related classes

---

CHANGELOG.md
Classes/Configuration/ConfigurationCheck.php
Classes/Database/DatabaseService.php
Classes/Language/SalutationSwitcher.php
Tests/Unit/Mapper/MapperRegistryTest.php
phpstan-baseline.neon

In addition to silencing warnings, also add a missing call parameter.

[CLEANUP] Fix all PHPStan level 0 warnings

---

CHANGELOG.md
Classes/Templating/TemplateHelper.php
Classes/ViewHelpers/GoogleMapsViewHelper.php
Tests/Unit/ViewHelpers/GoogleMapsViewHelperTest.php

This is not needed anymore with modern HTML versions.
Fixes #630

[TASK] Drop `type="text/javascript"` from `script` tags

---

CHANGELOG.md
Classes/Domain/Repository/GermanZipCodeRepository.php
Classes/Domain/Repository/Traits/ReadOnly.php
Classes/Domain/Repository/Traits/ReadOnlyRepository.php
Tests/Unit/Domain/Repository/Fixtures/ReadOnlyRepository.php

The new Trait now is named `ReadOnlyRepository`.
(The old name breaks compatibility with PHP 8.1.)
Fixes #621

[TASK] Deprecate the `ReadOnly` trait

---

Classes/Authentication/FrontEndLoginManager.php
Classes/Database/DatabaseService.php
Classes/Testing/TestingFramework.php
Tests/Functional/Configuration/ConfigurationRegistryTest.php
Tests/Functional/Database/DatabaseServiceTest.php
Tests/Functional/Testing/TestingFrameworkTest.php
phpstan-baseline.neon

PHPStan runs with TYPO3 9LTS and hence does not recognize the 8LTS code.

[CLEANUP] Silence PHPStan warnings for TYPO3 8LTS

---

composer.json

The `static_info_tables` extension requires the extension manager,
but does not declare this as a dependency.
Declare this missing dependecy as a dev dependency now in order to
avoid test breakage as a workaround.

[BUGFIX] Require an extension needed for the tests

---

.gitattributes
.github/workflows/release.yml
CHANGELOG.md
Resources/Private/Patches/testing-framework/faster-truncate.diff
composer.json

We will be able to drop this change once the nimut testing framework
has adopted this change.

[TASK] Truncate changed tables only for functional tests

---

.gitattributes
CHANGELOG.md

When this extension is used via Composer, there is no need to package
its own Composer dependencies anymore.
Fixes #647

[BUGFIX] Stop packaging the included Composer packages

---

CHANGELOG.md
Classes/Mapper/BackEndUserGroupMapper.php
Classes/Mapper/BackEndUserMapper.php
Classes/Mapper/FrontEndUserGroupMapper.php
Classes/Mapper/FrontEndUserMapper.php

This has proven to not work, and so we should remove it.
This reverts commit 8953ec05e14405ba8286b3927ef9a5eb1817acdc.

[TASK] Stop making the mapper generics extendable

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php
Classes/Configuration/ConfigurationCheck.php
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
Tests/Unit/Configuration/ConfigurationCheckTest.php

This makes copy'n'pasting the allowed values a lot easier.
Fixes #684

[TASK] Show allowed configuration values without enclosing quotes

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php
Tests/Unit/Configuration/AbstractConfigurationCheckTest.php

Now the value also is display for "multi in set" contraints.

[BUGFIX] Always display the incorrect value in the configuration check

---

CHANGELOG.md
Classes/Interfaces/ConfigurationCheckable.php

This interface was only needed for the legacy configuration check
(which will be removed in oelib 4.0).
Fixes #765

[TASK] Deprecate `ConfigurationCheckable`

---

CHANGELOG.md
Tests/Functional/Configuration/ConfigurationRegistryTest.php

This fixes these tests in TYPO3 10LTS.
Fixes #488

[BUGFIX] Disable the Core caches for some functional tests

---

CHANGELOG.md
Classes/Mapper/MapperRegistry.php
Tests/Unit/Mapper/MapperRegistryTest.php
phpstan-baseline.neon

Composer autoloading it case-sensitive. So we must not lowercase the class names.
Fixes #786

[TASK] Handle mapper names in a case-sensitives way in the `MapperRegistry`

---

CHANGELOG.md
Classes/DataStructures/Collection.php
Classes/Logging/Interfaces/LoggingAware.php
Tests/Functional/Mapper/AbstractDataMapperTest.php
phpstan-baseline.neon

https://github.com/phpstan/phpstan/issues/3526#issuecomment-648011497
https://dev.to/suckup_de/generics-in-php-via-phpdocs-1094
https://github.com/phpstan/phpstan-src/pull/301

[CLEANUP] Add more type annotations

---

CHANGELOG.md
Classes/Authentication/BackEndLoginManager.php
Classes/Authentication/FrontEndLoginManager.php
Classes/Interfaces/LoginManager.php

These methods cannot provide meaningful type annotations and hence
are a problem.

[TASK] Deprecate `*LoginManager::getLoggedInUser()`

---

composer.json
phpstan-baseline.neon

Also remove obsolete entries from the PHPStan baseline due to the
latest changes in TYPO3 V10.

[TASK] Upgrade PHPStan

---

composer.json

This is required for Composer 2.2.

[BUGFIX] Explicitly enable the required Composer plugins

---

CHANGELOG.md
composer.json
ext_emconf.php

We are using the `Typo3Version` class which was added in TYPO3
9.5.16.

[BUGFIX] Require TYPO3 >= 9.5.16 to avoid missing classes

---

CHANGELOG.md
composer.json

Require TYPO3 ^10.4.1 for TYPO3 10LTS to avoid running into a problem
where the `Query` instance cannot be injected.

[BUGFIX] Avoid DI-related exception in TYPO3 10LTS

---

CHANGELOG.md
Classes/Domain/Repository/Traits/StoragePageAgnostic.php

`ObjectManager` has been deprecated in TYPO3 V11.

[BUGFIX] Stop using the deprecated `ObjectManager` in a trait

---

CHANGELOG.md
composer.json

Do not depend on transitive dependencies.

[BUGFIX] Make the Composer dependencies explicit

---

CHANGELOG.md
Classes/Testing/TestingFramework.php
Tests/Functional/Testing/TestingFrameworkTest.php

This keeps previous request instances from spilling over into the next
test.

[BUGFIX] Discard the previous global request with the fake FE

---

CHANGELOG.md
Classes/Mapper/AbstractDataMapper.php
Tests/Functional/Mapper/AbstractDataMapperTest.php

The method already worked fine (as proven by the new tests),
but the new implementation is cleaner.
Fixes #909

[TASK] Harden `AbstractDataMapper::findByPageUid`

---

CHANGELOG.md
composer.json

After the removal of the email-related classes in #694,
the SwiftMailer dependency is no longer necessary.

[CLEANUP] Drop the outdated SwiftMailer dependency

---

CHANGELOG.md
Classes/Templating/TemplateHelper.php
Tests/Unit/Templating/TemplateHelperTest.php

This mostly affects unit tests with a minimal setup in other extensions.

[BUGFIX] Allow a `TemplateHelper` Configuration without cObj

---

.gitattributes
.github/workflows/codecoverage.yml
.gitignore
.phive/phars.xml
CHANGELOG.md
composer.json

This avoids problems with `composer install` with the current PHP
version span we support.

[TASK] Move PHPCov to PHIVE

---

CHANGELOG.md
Tests/Functional/Testing/TestingFrameworkTest.php

This check is not really relevant, and it is version-specific. So
let's remove it.
Fixes #957

[TASK] Stop testing that the fake FE has `sys_page`

---

CHANGELOG.md
Tests/Functional/Testing/TestingFrameworkTest.php

The result is version-specific and unrelated to our code anyway.
Fixes #959

[TASK] Stop testing the result of `getIndpEnv` for `PATH_INFO`

---

CHANGELOG.md
Classes/Configuration/AbstractConfigurationCheck.php
Classes/Domain/Repository/PageRepository.php
Classes/Mapper/AbstractDataMapper.php
Classes/Mapper/FrontEndUserMapper.php
Classes/Testing/CacheNullifyer.php
Classes/Testing/TestingFramework.php
Tests/Functional/Testing/CacheNullifyerTest.php
Tests/Functional/Testing/TestingFrameworkTest.php
Tests/Unit/Geocoding/GoogleGeocodingTest.php

[BUGFIX] Avoid using deprecated classes and methods

---

CHANGELOG.md
Classes/Mapper/AbstractDataMapper.php
Classes/Mapper/BackEndUserGroupMapper.php
Classes/Mapper/BackEndUserMapper.php
Classes/Mapper/CountryMapper.php
Classes/Mapper/CurrencyMapper.php
Classes/Mapper/FederalStateMapper.php
Classes/Mapper/FrontEndUserGroupMapper.php
Classes/Mapper/FrontEndUserMapper.php
Classes/Mapper/LanguageMapper.php
Tests/Unit/Mapper/Fixtures/ColumnLessTestingMapper.php
Tests/Unit/Mapper/Fixtures/ModelLessTestingMapper.php
Tests/Unit/Mapper/Fixtures/TableLessTestingMapper.php
Tests/Unit/Mapper/Fixtures/TestingChildMapper.php
Tests/Unit/Mapper/Fixtures/TestingMapper.php
phpstan-baseline.neon

Also make some type annotations more specific.
Fixes #1004

[CLEANUP] Drop redundant property type annotations for mappers

---

Classes/Templating/TemplateHelper.php

After some code cleanup gone bad, `TemplateHelper::getConfValue`
failed to fall back to the value from TypoScript if the value
from the flexforms was an empty string or zero.
This fixes a crash in the seminars list view due to the HTML template
not getting loaded anymore.
Fixes #1034

[BUGFIX] Properly check for falsey configuration values

---

composer.json

PHPUnit has dropped its dependency on Prophecy. In order to keep using
Prophecy in our tests, we need to add it as an explicit (development)
dependency.
Also, relying on transitive dependencies is bad practice anyway.

[BUGFIX] Explicitly require Prophecy

---

CHANGELOG.md
Classes/Domain/Repository/Traits/StoragePageAgnostic.php

Query settings are not supposed to get injected in repositories,
and injecting them will cause warnings that get logged.

[BUGFIX] Stop injecting the query settings in repositories

---

.github/workflows/ci.yml
.github/workflows/codecoverage.yml
CHANGELOG.md

This unblocks using the development version of TYPO3.
Fixes #1053

[TASK] Require typo3/cms-core instead of typo3/minimal on CI

---

CHANGELOG.md
Classes/Visibility/Node.php
Classes/Visibility/Tree.php

Those classes are not used anymore.
Fixes #561

[TASK] Deprecate the visibility-related `Node` and `Tree`

---

CHANGELOG.md
Tests/Functional/Validation/AbstractConfigurationDependentValidatorTest.php
Tests/Functional/Validation/Fixtures/TestingConfigurationDependentValidator.php
Tests/Functional/Validation/Fixtures/TestingValidatableModel.php
phpstan-baseline.neon

This is in preparation for making the validation error messages localizable.

[TASK] Move the validator tests to functional tests

---

CHANGELOG.md
Configuration/TCA/Overrides/fe_users.php
Configuration/TCA/tx_oelib_domain_model_germanzipcode.php
Configuration/TCA/tx_oelib_test.php
Configuration/TCA/tx_oelib_testchild.php
TestExtensions/user_oelibtest/Configuration/TCA/user_oelibtest_test.php
TestExtensions/user_oelibtest2/Configuration/TCA/user_oelibtest2_test.php
ext_localconf.php

[BUGFIX] Use the `TYPO3` constant instead of `TYPO3_MODE`

---

composer.json

We're not using this package here anymore.

[TASK] Drop the `mikey179/vfsstream` dependency

---

CHANGELOG.md
Tests/Functional/Domain/Repository/GermanZipCodeRepositoryTest.php

[BUGFIX] Stop using the deprecated `ObjectManager` in 11LTS

---

Tests/Functional/Model/AbstractModelTest.php
Tests/Functional/Model/FrontEndUserTest.php
phpstan-baseline.neon

[TASK] Stop using `$this->getDatabaseConnection()` in tests (part 1)

---

Tests/Functional/Mapper/CountryMapperTest.php
Tests/Functional/Mapper/CurrencyMapperTest.php
Tests/Functional/Mapper/FederalStateMapperTest.php
Tests/Functional/Mapper/LanguageMapperTest.php
Tests/Functional/Model/AbstractModelTest.php

[TASK] Stop using `$this->getDatabaseConnection()` in tests (part 2)

---

CHANGELOG.md
Classes/Testing/TestingFramework.php
Tests/Functional/Testing/TestingFrameworkTest.php
phpstan-baseline.neon

It's not used anymore in other extensions.
Fixes #1146

[TASK] Drop `$additionalTablePrefixes` from testing framework

---

CHANGELOG.md
Classes/Testing/TestingFramework.php
Tests/Functional/Testing/TestingFrameworkTest.php
phpstan-baseline.neon

Getting the auto increment value does not work as before in MySQL 8 (which is used for the ubuntu-20 and ubuntu-22 runners on GitHub actions) anymore.
We'll deprecate this functionality and do damage control until it is removed.
Fixes #1162

[TASK] Only work on the auto increment value if the DB supports it

---

Tests/Functional/Mapper/AbstractDataMapperTest.php

[TASK] Replace UPDATE queries in `AbstractDataMapperTest`

---

Classes/Mapper/AbstractDataMapper.php
Tests/Functional/Mapper/AbstractDataMapperTest.php
phpstan-baseline.neon

Also improve the type annotations in `AbstractDataMapper` a bit.
Part of #1142

[TASK] Replace SELECT queries in `AbstractDataMapperTest`

---

CHANGELOG.md
composer.json

This is required to avoid some crashes in the testing framework.

[TASK] Raise the minimal 11LTS version to 11.5.4

---

.github/workflows/ci.yml

This avoids YAML rounding PHP 8.0 to "version 8".

[BUGFIX] Always quote version numbers in the CI configuration

---

.github/workflows/ci.yml
.github/workflows/codecoverage.yml

Usually the testing framework automatically does this, but there seems to be a race condition resulting in the directory not getting created.
Fixes #1183

[BUGFIX] Always create the tests directory on CI

---

CHANGELOG.md
Classes/ViewHelpers/PriceViewHelper.php
Tests/Functional/ViewHelpers/PriceViewHelperTest.php
Tests/Unit/ViewHelpers/PriceViewHelperTest.php

This view helper is still used in the seminars extensions and should note have been removed.
This mostly reverts commit 37a8483a972e9830d042b8c4b477a47f6c099b9a.
Fixes #1193

[BUGFIX] Reinstantiate the `PriceViewHelper`

---

Classes/Model/FrontEndUser.php

`strftime` has been deprecated in PHP 8.1.
Fixes #1203

[BUGFIX] Stop using the deprecated `strftime`

---

CHANGELOG.md
Classes/ViewHelpers/AbstractConfigurationCheckViewHelper.php

This is deprecated in PHP 8.2.

[BUGFIX] Stop using `static` in callables

---

.github/workflows/ci.yml

We need some bug fixes in newer versions of the dependencies to have the PHP 8.2 build warning-free.

[TASK] Do not run the PHP 8.2 tests with the lowest dependencies

---

CHANGELOG.md
Configuration/TCA/tx_oelib_test.php
Configuration/TCA/tx_oelib_testchild.php

These tables cannot be created manually in the BE anyway.

[BUGFIX] Remove the deprecated `cruser_id` configuration for test tables

---

Tests/Functional/Templating/TemplateRegistryTest.php
Tests/Functional/Templating/TemplateTest.php
Tests/Unit/Templating/TemplateRegistryTest.php
Tests/Unit/Templating/TemplateTest.php

For TYPO3 12LTS, we need functional tests for theses tests in order to resolved loaded extensions.

[TASK] Move some templating tests to functionals

---

CHANGELOG.md
Classes/Language/SalutationSwitcher.php
Tests/Functional/Language/Fixtures/TestingSalutationSwitcher.php
phpstan-baseline.neon

This part is about making the (deprecated) `SalutationSwitcher` independent from `AbstractPlugin`.

[TASK] Stop extending the deprecated `AbstractPlugin` (part 1)

---

CHANGELOG.md
Classes/Language/SalutationSwitcher.php
Classes/Templating/TemplateHelper.php
phpstan-baseline.neon

This part is about making the `TemplateHelper`
independent from `AbstractPlugin`.

[TASK] Stop extending the deprecated `AbstractPlugin` (part 2)

---

CHANGELOG.md
Configuration/Services.yaml

[BUGFIX] Mark the `Configuration` classes as non-injectable

---

CHANGELOG.md
Classes/Testing/TestingFramework.php
Tests/Functional/Testing/TestingFrameworkTest.php

This change was potentially breaking. We should replace it with something functional instead at a later point.
This reverts commit 43c0bf9abf2e0d4bb7c09c0440a146f0df943ec4.
Fixes #1515

[TASK] Re-enable the legacy template parsing

---

.gitattributes
Configuration/FunctionalTests.xml
Configuration/UnitTests.xml
composer.json

Also disable deprecation warnings for the functional tests.
Fixes #1516

[TASK] Use our own copy of the PHPUnit configuration files

---

CHANGELOG.md
Classes/Mapper/CurrencyMapper.php
Classes/Model/Currency.php
Classes/ViewHelpers/PriceViewHelper.php

Those are still in use in seminars.

[TASK] De-deprecate `Currency` model/mapper and `PriceViewHelper`

---

CHANGELOG.md
Classes/Model/FrontEndUser.php
Tests/Unit/Model/FrontEndUserTest.php

A username is not a meaningful substitute for a real name after all.
Fixes #1586

[BUGFIX] Return empty string in `FrontEndUser::getName()` for no name

---

CHANGELOG.md
Classes/Mapper/AbstractDataMapper.php
Classes/Mapper/MapperRegistry.php
Tests/Unit/Mapper/AbstractDataMapperTest.php
Tests/Unit/Mapper/Fixtures/TestingMapper.php

Also drop some now-unused properties and a meaningless test.
Fixes #1583

[TASK] Reduce the visibility of some `AbstractDataMapper` properties

---

.github/dependabot.yml
composer.json

Also drop the workaround for older versions of PHP-CS-Fixer with PHP 8.2.
Fixes #1439

[TASK] Bump the development dependencies

---

CHANGELOG.md
Classes/Mapper/AbstractDataMapper.php
Tests/Functional/Mapper/AbstractDataMapperTest.php
Tests/Functional/Testing/TestingFrameworkTest.php
phpstan-baseline.neon

[TASK] Avoid using the deprecated `fetch()` for DB results

---

CHANGELOG.md
Classes/Domain/Repository/PageRepository.php

[BUGFIX] Stop using the deprecated `Connection::PARAM_INT_ARRAY`

---

CHANGELOG.md
Tests/Functional/Mapper/AbstractDataMapperTest.php
Tests/Unit/Model/AbstractModelTest.php

This removes the last occurrence of `$GLOBALS['SIM_EXEC_TIME']`.
Fixes #1683

[BUGFIX] Properly set the `DateTimeAspect` in the tests

---

CHANGELOG.md
Resources/Private/Language/locallang.xlf
Resources/Private/Language/locallang_db.xlf

Approving only applies to translations, not to the original English labels.
Fixes #1783

[TASK] Drop `approved="yes"` from the English locallang files

---

README.md

The counter only shows the downloads on Packagist. For TYPO3 extensions, this is incomplete information and hence not really useful.
Fixes #1855
[ci skip]

[TASK] Remove the download counter

---

Configuration/TCA/tx_oelib_testchild.php

[BUGFIX] Use booleans for `exclude` in TCA

---

CHANGELOG.md
Classes/Mapper/AbstractDataMapper.php

This removes a deprecation warning with PHP 8.4.
Fixes #1961

[BUGFIX] Make implicit nullable parameter explicit

---

phpstan-baseline.neon
phpstan.neon

This removes one obstacle for upgrading to PHPStan 2.
Fixes #1967

[TASK] Allow `instanceOf` checks in a test in a different way

---

CHANGELOG.md
Classes/DataStructures/AbstractObjectWithPublicAccessors.php
Classes/DataStructures/AbstractReadOnlyObjectWithAccessors.php
Classes/DataStructures/AbstractReadOnlyObjectWithPublicAccessors.php
Tests/Unit/DataStructures/AbstractReadOnlyObjectWithAccessorsTest.php

Follow up to #1988
Part of #2007

[BUGFIX] Move `getAs*Integer` to the correct superclass
